FUNCTION ZFM_BM_CS_SALES_ORG_SD71.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD71
*"----------------------------------------------------------------------
  DATA: LSS_TVFK         TYPE TVFK.

  GS_DATASD71 = I_DATA.
  SELECT SINGLE
    *
      FROM TVFK
       INTO CORRESPONDING FIELDS OF  GT_SD71
      WHERE FKART = GS_DATASD71-FKART.
  IF SY-SUBRC IS INITIAL.
    GS_SD71-FKART = GS_DATASD71-FKART.
    GS_SD71-KALSMC = GS_DATASD71-KALSMC.
    GS_SD71-KVSLV = GS_DATASD71-KVSLV.
    MOVE-CORRESPONDING GS_SD71 TO LSS_TVFK.
    UPDATE  TVFK FROM LSS_TVFK.
  ELSE.
    GS_SD71-FKART = GS_DATASD71-FKART.
    GS_SD71-KALSMC = GS_DATASD71-KALSMC.
    GS_SD71-KVSLV = GS_DATASD71-KVSLV.
    MOVE-CORRESPONDING GS_SD71 TO LSS_TVFK.
    INSERT  TVFK FROM LSS_TVFK.
  ENDIF.
ENDFUNCTION.
