FUNCTION ZFM_BM_CS_SALES_ORG_SD106.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD106
*"----------------------------------------------------------------------

  DATA: LSS_TVKOV     TYPE TVKOV.

  GS_DATASD106 = I_DATA.
  SELECT SINGLE
    *
      FROM TVKOV
       INTO CORRESPONDING FIELDS OF  GT_SD106
      WHERE VKORG = GS_DATASD106-VKORG .
  IF SY-SUBRC IS INITIAL.
    GS_SD106-VKORG = GS_DATASD106-VKORG.
    GS_SD106-VTWEG = GS_DATASD106-VTWEG.
    GS_SD106-VTWAU = GS_DATASD106-VTWAU.

    MOVE-CORRESPONDING GS_SD106 TO LSS_TVKOV.
    UPDATE  TVKOV FROM LSS_TVKOV.

  ELSE.
    GS_SD106-VKORG = GS_DATASD106-VKORG.
    GS_SD106-VTWEG = GS_DATASD106-VTWEG.
    GS_SD106-VTWAU = GS_DATASD106-VTWAU.

    MOVE-CORRESPONDING GS_SD106 TO LSS_TVKOV.
    INSERT  TVKOV FROM LSS_TVKOV.
  ENDIF.
ENDFUNCTION..
