FUNCTION ZFM_BM_CS_SALES_ORG_SD59.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD59
*"----------------------------------------------------------------------
  DATA: LSS_TVTA       TYPE TVTA.

  GS_DATASD59 = I_DATA.
  SELECT SINGLE
    *
      FROM TVTA
       INTO CORRESPONDING FIELDS OF  GT_SD59
      WHERE VKORG = GS_DATASD59-VKORG
    AND VTWEG = GS_DATASD59-VTWEG
    AND SPART =  GS_DATASD59-SPART.
  IF SY-SUBRC IS INITIAL.
    GS_SD59-VKORG = GS_DATASD59-VKORG.
    GS_SD59-VTWEG = GS_DATASD59-VTWEG.
    GS_SD59-SPART = GS_DATASD59-SPART.
    GS_SD59-REGGB = GS_DATASD59-REGGB.

    MOVE-CORRESPONDING GS_SD59 TO LSS_TVTA.
    UPDATE  TVTA FROM LSS_TVTA.

  ELSE.
    GS_SD59-VKORG = GS_DATASD59-VKORG.
    GS_SD59-VTWEG = GS_DATASD59-VTWEG.
    GS_SD59-SPART = GS_DATASD59-SPART.
    GS_SD59-REGGB = GS_DATASD59-REGGB.

    MOVE-CORRESPONDING GS_SD59 TO LSS_TVTA.
    INSERT  TVTA FROM LSS_TVTA.
  ENDIF.
ENDFUNCTION.
