FUNCTION ZFM_BM_CS_SALES_ORG_SDD193.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD193
*"----------------------------------------------------------------------
DATA:
         LSS_TVTK TYPE TVTK.
  GS_DATASD193 = I_DATA.
  SELECT SINGLE *
    FROM TVTK
    INTO CORRESPONDING FIELDS OF GT_SD193
    WHERE SHTYP = GS_DATASD193-SHTYP.
  IF  SY-SUBRC IS INITIAL.
    GS_SD193-SHTYP = GS_DATASD193-SHTYP.
    GS_SD193-FRKRL = GS_DATASD193-FRKRL.
    GS_SD193-FRKRL_STR = GS_DATASD193-FRKRL_STR.
    GS_SD193-FRKRL_UMP = GS_DATASD193-FRKRL_UMP.
    GS_SD193-FRKRL_GRP = GS_DATASD193-FRKRL_GRP.

    MOVE-CORRESPONDING GS_SD193 TO LSS_TVTK.
    UPDATE TVTK FROM LSS_TVTK.
  ELSE.
  GS_SD193-SHTYP = GS_DATASD193-SHTYP.
    GS_SD193-FRKRL = GS_DATASD193-FRKRL.
    GS_SD193-FRKRL_STR = GS_DATASD193-FRKRL_STR.
    GS_SD193-FRKRL_UMP = GS_DATASD193-FRKRL_UMP.
    GS_SD193-FRKRL_GRP = GS_DATASD193-FRKRL_GRP.

    MOVE-CORRESPONDING GS_SD193 TO LSS_TVTK.
    INSERT TVTK FROM LSS_TVTK.
  ENDIF.
ENDFUNCTION.
