FUNCTION ZFM_BM_CS_SALES_ORG_SD61.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD61
*"----------------------------------------------------------------------
  DATA: LSS_TVTA       TYPE TVTA.

  GS_DATASD61 = I_DATA.
  SELECT SINGLE
    *
      FROM TVTA
       INTO CORRESPONDING FIELDS OF  GT_SD61
      WHERE VKORG = GS_DATASD61-VKORG
    AND VTWEG = GS_DATASD61-VTWEG
    AND SPART =  GS_DATASD61-SPART.
  IF SY-SUBRC IS INITIAL.
    GS_SD61-VKORG = GS_DATASD61-VKORG.
    GS_SD61-VTWEG = GS_DATASD61-VTWEG.
    GS_SD61-SPART = GS_DATASD61-SPART.
    GS_SD61-GSBER = GS_DATASD61-GSBER.

    MOVE-CORRESPONDING GS_SD61 TO LSS_TVTA.
    UPDATE  TVTA FROM LSS_TVTA.

  ELSE.
    GS_SD61-VKORG = GS_DATASD61-VKORG.
    GS_SD61-VTWEG = GS_DATASD61-VTWEG.
    GS_SD61-SPART = GS_DATASD61-SPART.
    GS_SD61-GSBER = GS_DATASD61-GSBER.

    MOVE-CORRESPONDING GS_SD61 TO LSS_TVTA.
    INSERT  TVTA FROM LSS_TVTA.
  ENDIF.
ENDFUNCTION.
