FUNCTION ZFM_BM_CS_SALES_ORG_SDD126.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD126
*"----------------------------------------------------------------------

DATA : LSS_T6B2F TYPE T6B2F.
GS_DATASD126 = I_DATA.

SELECT SINGLE
  *
  FROM T6B2F
  INTO CORRESPONDING FIELDS OF GT_SD125
  WHERE KAPPL = 'V'
  AND KOBOG = GS_DATASD126-KOBOG
  AND  ZAEHK = GS_DATASD126-ZAEHK.
  IF  SY-SUBRC IS INITIAL.
    GS_SD126-KAPPL = 'V'.
    GS_SD126-KOBOG = GS_DATASD126-KOBOG.
    GS_SD126-ZAEHK = GS_DATASD126-ZAEHK.
    GS_SD126-KSCHL = GS_DATASD126-KSCHL.
    GS_SD126-KOTABNR = GS_DATASD126-KOTABNR.
    MOVE-CORRESPONDING GS_SD126 TO LSS_T6B2F.
    UPDATE T6B2F FROM LSS_T6B2F.
    ELSE.
       GS_SD126-KAPPL = 'V'.
    GS_SD126-KOBOG = GS_DATASD126-KOBOG.
    GS_SD126-ZAEHK = GS_DATASD126-ZAEHK.
    GS_SD126-KSCHL = GS_DATASD126-KSCHL.
    GS_SD126-KOTABNR = GS_DATASD126-KOTABNR.
    MOVE-CORRESPONDING GS_SD126 TO LSS_T6B2F.
    INSERT T6B2F FROM LSS_T6B2F.

  ENDIF.



ENDFUNCTION.
