FUNCTION ZFM_BM_CS_SALES_ORG_SD51 .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD52
*"----------------------------------------------------------------------


  DATA: LSS_TVFK        TYPE TVFK.

  GS_DATASD52 = I_DATA.
  SELECT SINGLE
    *
      FROM TVFK
       INTO CORRESPONDING FIELDS OF  GT_SD52
      WHERE FKART = GS_DATASD52-FKART.
  IF SY-SUBRC IS INITIAL.
    GS_SD52-FKART = GS_DATASD52-FKART.
    GS_SD52-PARGK = GS_DATASD52-PARGK.
    MOVE-CORRESPONDING GS_SD52 TO LSS_TVFK.
    UPDATE  TVFK FROM LSS_TVFK.

  ELSE.
    GS_SD52-FKART = GS_DATASD52-FKART.
    GS_SD52-PARGK = GS_DATASD52-PARGK.
    MOVE-CORRESPONDING GS_SD52 TO LSS_TVFK.
    INSERT  TVFK FROM LSS_TVFK.
  ENDIF.
ENDFUNCTION.
