FUNCTION ZFM_BM_CS_SALES_ORG_SDD175.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD175
*"----------------------------------------------------------------------
DATA:
         LSS_T503Z TYPE T503Z.
  GS_DATASD175 = I_DATA.
  SELECT SINGLE *
    FROM T503Z
    INTO CORRESPONDING FIELDS OF GT_SD175
    WHERE PERSG = GS_DATASD175-PERSG
    AND PERSK = GS_DATASD175-PERSK
    AND MOLGA = '29'.
  IF  SY-SUBRC IS INITIAL.
    GS_SD175-PERSG = GS_DATASD175-PERSG.
    GS_SD175-PERSK = GS_DATASD175-PERSK.
    GS_SD175-MOLGA = '29'.
    MOVE-CORRESPONDING GS_SD175 TO LSS_T503Z.
    UPDATE T503Z FROM LSS_T503Z.
  ELSE.
  GS_SD175-PERSG = GS_DATASD175-PERSG.
    GS_SD175-PERSK = GS_DATASD175-PERSK.
    GS_SD175-MOLGA = '29'.
    MOVE-CORRESPONDING GS_SD175 TO LSS_T503Z.
    INSERT T503Z FROM LSS_T503Z.
  ENDIF.
ENDFUNCTION.
