FUNCTION ZFM_BM_CS_SALES_ORG_SD55 .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD56
*"----------------------------------------------------------------------
DATA: LSS_TSTL       TYPE TSTL.

  GS_DATASD56 = I_DATA.
  SELECT SINGLE
    *
      FROM TSTL
       INTO CORRESPONDING FIELDS OF  GT_SD56
      WHERE TALND = GS_DATASD56-TALND
    AND LFDNR = GS_DATASD56-LFDNR.
  IF SY-SUBRC IS INITIAL.
    GS_SD56-TALND = GS_DATASD56-TALND.
    GS_SD56-LFDNR = GS_DATASD56-LFDNR.
    GS_SD56-TATYP = GS_DATASD56-TATYP.

    MOVE-CORRESPONDING GS_SD56 TO LSS_TSTL.
    UPDATE  TSTL FROM LSS_TSTL.

  ELSE.
      GS_SD56-TALND = GS_DATASD56-TALND.
    GS_SD56-LFDNR = GS_DATASD56-LFDNR.
    GS_SD56-TATYP = GS_DATASD56-TATYP.

    MOVE-CORRESPONDING GS_SD56 TO LSS_TSTL.
    INSERT  TSTL FROM LSS_TSTL.
  ENDIF.
ENDFUNCTION.
