FUNCTION ZFM_BM_CS_SALES_ORG_SDD195.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD195
*"----------------------------------------------------------------------
DATA:
         LSS_T173 TYPE T173.
  GS_DATASD195 = I_DATA.
  SELECT SINGLE *
    FROM T173
    INTO CORRESPONDING FIELDS OF GT_SD195
    WHERE VSART = GS_DATASD195-VSART.
  IF  SY-SUBRC IS INITIAL.
    GS_SD195-VSART = GS_DATASD195-VSART.
    GS_SD195-VSGRP = GS_DATASD195-VSGRP.
    MOVE-CORRESPONDING GS_SD195 TO LSS_T173.
    UPDATE T173 FROM LSS_T173.
  ELSE.
   GS_SD195-VSART = GS_DATASD195-VSART.
    GS_SD195-VSGRP = GS_DATASD195-VSGRP.
    MOVE-CORRESPONDING GS_SD195 TO LSS_T173.
    INSERT T173 FROM LSS_T173.
  ENDIF.
ENDFUNCTION.
