FUNCTION-POOL ZFG_BM_CS_CO.                 "MESSAGE-ID ..

* INCLUDE LZFG_BM_CS_COD...                  " Local class definition
DATA:
     GS_DATA05_OKKP TYPE ZST_BM_SALES_05_OKKP,
     GS_DATA04_OKKP TYPE ZST_BM_CS_04_OKKP,
     GT_04_OKKP TYPE ZST_BM_CS_04_OKKP,
     GS_04_OKKP TYPE ZST_BM_CS_04_OKKP,
     GT_05_OKKP TYPE ZST_BM_SALES_05_OKKP,
     GS_05_OKKP TYPE ZST_BM_SALES_05_OKKP.
