FUNCTION ZFM_BM_CS_SALES_ORG_SDD125.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SDD125
*"----------------------------------------------------------------------
  DATA:
        LSS_T6B2  TYPE T6B2.
  GS_DATASD125 = I_DATA.
  SELECT SINGLE *
    FROM T6B2
    INTO CORRESPONDING FIELDS OF GT_SD125
    WHERE KAPPL = 'V'.
  IF  SY-SUBRC IS INITIAL.
    GS_SD125-KAPPL = 'V'.
    GS_SD125-KOBOG = GS_DATASD125-KOBOG.
    GS_SD125-KOGRUTY = GS_DATASD125-KOGRUTY.
    MOVE-CORRESPONDING GS_SD125 TO LSS_T6B2.
    UPDATE T6B2 FROM LSS_T6B2.
  ELSE.
    GS_SD125-KAPPL = 'V'.
    GS_SD125-KOBOG = GS_DATASD125-KOBOG.
    GS_SD125-KOGRUTY = GS_DATASD125-KOGRUTY.
    MOVE-CORRESPONDING GS_SD125 TO LSS_T6B2.
    INSERT T6B2 FROM LSS_T6B2.

  ENDIF.
ENDFUNCTION.
