FUNCTION ZFM_BM_CS_SALES_ORG_SDD147.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD147
*"----------------------------------------------------------------------
 DATA:
         LSS_TVLP TYPE TVLP.
  GS_DATASD147 = I_DATA.
  SELECT SINGLE *
    FROM TVLP
    INTO CORRESPONDING FIELDS OF GT_SD147
    WHERE PSTYV = GS_DATASD147-PSTYV.
  IF  SY-SUBRC IS INITIAL.
    GS_SD147-PSTYV = GS_DATASD147-PSTYV.
    GS_SD147-CHAUT = GS_DATASD147-CHAUT.
    MOVE-CORRESPONDING GS_SD147 TO LSS_TVLP.
    UPDATE TVLP FROM LSS_TVLP.
  ELSE.
    GS_SD147-PSTYV = GS_DATASD147-PSTYV.
    GS_SD147-CHAUT = GS_DATASD147-CHAUT.
    MOVE-CORRESPONDING GS_SD147 TO LSS_TVLP.
    INSERT TVLP FROM LSS_TVLP.

  ENDIF.
ENDFUNCTION.
