FUNCTION ZFM_BM_CS_SALES_ORG_SDD155.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD155
*"----------------------------------------------------------------------
DATA:
         LSS_TVAK TYPE TVAK.
  GS_DATASD155 = I_DATA.
  SELECT SINGLE *
    FROM TVAK
    INTO CORRESPONDING FIELDS OF GT_SD155
    WHERE AUART = GS_DATASD155-AUART.
  IF  SY-SUBRC IS INITIAL.
    GS_SD155-AUART = GS_DATASD155-AUART.
    GS_SD155-KLIMP = GS_DATASD155-KLIMP.
    GS_SD155-CMGRA = GS_DATASD155-CMGRA.
    MOVE-CORRESPONDING GS_SD155 TO LSS_TVAK.
    UPDATE TVAK FROM LSS_TVAK.
  ELSE.
   GS_SD155-AUART = GS_DATASD155-AUART.
    GS_SD155-KLIMP = GS_DATASD155-KLIMP.
    GS_SD155-CMGRA = GS_DATASD155-CMGRA.
    MOVE-CORRESPONDING GS_SD155 TO LSS_TVAK.
    INSERT TVAK FROM LSS_TVAK.

  ENDIF.
ENDFUNCTION.
