FUNCTION ZFM_BM_CS_SALES_ORG_SD85.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD85
*"----------------------------------------------------------------------

  DATA: LSS_TVFK           TYPE TVFK.

  GS_DATASD85 = I_DATA.
  SELECT SINGLE
    *
      FROM TVFK
       INTO CORRESPONDING FIELDS OF  GT_SD85
      WHERE FKART = GS_DATASD85-FKART .
  IF SY-SUBRC IS INITIAL.
    GS_SD85-FKART = GS_DATASD85-FKART.
    GS_SD85-KALVG = GS_DATASD85-KALVG.
    MOVE-CORRESPONDING GS_SD85 TO LSS_TVFK.
    UPDATE  TVFK FROM LSS_TVFK.

  ELSE.
      GS_SD85-FKART = GS_DATASD85-FKART.
    GS_SD85-KALVG = GS_DATASD85-KALVG.
    MOVE-CORRESPONDING GS_SD85 TO LSS_TVFK.
    INSERT  TVFK FROM LSS_TVFK.
  ENDIF.
ENDFUNCTION.
