FUNCTION ZFM_BM_CS_SALES_ORG_SD17.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD17
*"----------------------------------------------------------------------
DATA: LSS_TVBVK           TYPE TVBVK,
        LS_TASSIGN_SD_VKBUR TYPE TASSIGN_SD_VKBUR.

  GS_DATASD17 = I_DATA.
  SELECT SINGLE
     TVBVK~VKBUR,
     TVBVK~VKGRP,
     TVBVK~HIDE,
     TASSIGN_SD_VKBUR~STATUS_ASSIGN_SD
     FROM TVBVK
     INNER JOIN TASSIGN_SD_VKBUR
     ON TASSIGN_SD_VKBUR~VKBUR = TVBVK~VKBUR
        INTO CORRESPONDING FIELDS OF  @GT_SD17
       WHERE TVBVK~VKBUR = @GS_DATASD17-VKBUR
     AND TVBVK~VKGRP = @GS_DATASD17-VKGRP.

  IF SY-SUBRC IS INITIAL.
    PERFORM CHECKSD17.
    GS_SD17-VKBUR = GS_DATASD17-VKBUR.
    GS_SD17-VKGRP = GS_DATASD17-VKGRP.
    GS_SD17-HIDE = GS_DATASD17-HIDE.
    MOVE-CORRESPONDING GS_SD17 TO LSS_TVBVK.
    MOVE-CORRESPONDING GS_SD17 TO LS_TASSIGN_SD_VKBUR.

    UPDATE  TVBVK FROM LSS_TVBVK.
    UPDATE  TASSIGN_SD_VKBUR FROM LS_TASSIGN_SD_VKBUR.
  ELSE.
    GS_SD17-VKBUR = GS_DATASD17-VKBUR.
    GS_SD17-VKGRP = GS_DATASD17-VKGRP.
    GS_SD17-HIDE = GS_DATASD17-HIDE.
    MOVE-CORRESPONDING GS_SD17 TO LSS_TVBVK.
    MOVE-CORRESPONDING GS_SD17 TO LS_TASSIGN_SD_VKBUR.

    INSERT TVBVK FROM LSS_TVBVK.
    INSERT  TASSIGN_SD_VKBUR FROM LS_TASSIGN_SD_VKBUR.
  ENDIF.
ENDFUNCTION.
FORM CHECKSD17.
  DATA:
    LS_TVBVK TYPE TVBVK,
    I_DATA   TYPE  ZST_BM_SALES_SD17.
  DATA: LSS_TVBVK           TYPE TVBVK,
        LS_TASSIGN_SD_VKBUR TYPE TASSIGN_SD_VKBUR.

  I_DATA = GS_DATASD17.
  SELECT SINGLE
    VKBUR
      FROM TVBVK
      INTO CORRESPONDING FIELDS OF  LS_TVBVK
      WHERE TVBVK~VKBUR = GS_DATASD17-VKBUR
      AND TVBVK~VKGRP = GS_DATASD17-VKGRP.

  IF SY-SUBRC IS INITIAL .
    IF GS_DATASD17-VKBUR  IS INITIAL
      AND GS_DATASD17-VKGRP  IS INITIAL
      AND GS_DATASD17-HIDE  IS INITIAL.
    ELSE.
      GS_SD17-VKBUR = GS_DATASD17-VKBUR.
    GS_SD17-VKGRP = GS_DATASD17-VKGRP.
    GS_SD17-HIDE = GS_DATASD17-HIDE.
    MOVE-CORRESPONDING GS_SD17 TO LSS_TVBVK.
    MOVE-CORRESPONDING GS_SD17 TO LS_TASSIGN_SD_VKBUR.

    UPDATE  TVBVK FROM LSS_TVBVK.
    UPDATE  TASSIGN_SD_VKBUR FROM LS_TASSIGN_SD_VKBUR.
    ENDIF.
  ENDIF.
ENDFORM.
