FUNCTION ZFM_BM_CS_SALES_ORG_SD79.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD79
*"----------------------------------------------------------------------
DATA: LSS_T682I TYPE T682I.

  GS_DATASD79 = I_DATA.
  SELECT SINGLE
    *
      FROM T682I

       INTO CORRESPONDING FIELDS OF  @GT_SD79
      WHERE T682I~KVEWE = @GS_DATASD79-KVEWE
    AND KAPPL = @GS_DATASD79-KAPPL
    AND KOZGF = @GS_DATASD79-KOZGF
    AND KOLNR = @GS_DATASD79-KOLNR.
  IF SY-SUBRC IS INITIAL.
    GS_SD79-KVEWE = 'A'.
    GS_SD79-KAPPL = 'V'.
    GS_SD79-KOZGF = GS_DATASD79-KOZGF.
    GS_SD79-KOLNR = GS_DATASD79-KOLNR.
    GS_SD79-KOTABNR = GS_DATASD79-KOTABNR.
    GS_SD79-KOBED = GS_DATASD79-KOBED.
    GS_SD79-KZEXL = GS_DATASD79-KZEXL.
    GS_SD79-KKOPF = 'X'.
    GS_SD79-GZUGR = GS_DATASD79-GZUGR.

    MOVE-CORRESPONDING GS_SD79 TO LSS_T682I.
    UPDATE  T682I FROM LSS_T682I.

  ELSE.
     GS_SD79-KVEWE = 'A'.
    GS_SD79-KAPPL = 'V'.
    GS_SD79-KOZGF = GS_DATASD79-KOZGF.
    GS_SD79-KOLNR = GS_DATASD79-KOLNR.
    GS_SD79-KOTABNR = GS_DATASD79-KOTABNR.
    GS_SD79-KOBED = GS_DATASD79-KOBED.
    GS_SD79-KZEXL = GS_DATASD79-KZEXL.
    GS_SD79-KKOPF = 'X'.
    GS_SD79-GZUGR = GS_DATASD79-GZUGR.

    MOVE-CORRESPONDING GS_SD79 TO LSS_T682I.
    INSERT  T682I FROM LSS_T682I.
  ENDIF.
ENDFUNCTION.
