FUNCTION ZFM_BM_CS_SALES_ORG_SD08.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD08
*"----------------------------------------------------------------------

  DATA: LSS_TVKO            TYPE TVKO,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  GS_DATASD08 = I_DATA.
  SELECT SINGLE
    TVKO~VKORG,
    TASSIGN_SD_VKORG~STATUS_ASSIGN_SD,
    TVKO~BUKRS
      FROM TVKO
    INNER JOIN TASSIGN_SD_VKORG
    ON TASSIGN_SD_VKORG~VKORG = TVKO~VKORG
       INTO CORRESPONDING FIELDS OF  @GT_SD08
      WHERE TVKO~VKORG = @GS_DATASD08-VKORG.
  IF SY-SUBRC IS INITIAL.
    PERFORM CHECKSD08.
    GS_SD08-VKORG = GS_DATASD08-VKORG.
    GS_SD08-BUKRS = GS_DATASD08-BUKRS.
    MOVE-CORRESPONDING GS_SD08 TO LSS_TVKO.
    MOVE-CORRESPONDING GS_SD08 TO LS_TASSIGN_SD_VKORG.

    UPDATE  TVKO FROM LSS_TVKO.
    UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ELSE.
    GS_SD08-VKORG = GS_DATASD08-VKORG.
    GS_SD08-BUKRS = GS_DATASD08-BUKRS.


    MOVE-CORRESPONDING GS_SD08 TO LSS_TVKO.
    MOVE-CORRESPONDING GS_SD08 TO LS_TASSIGN_SD_VKORG.

    INSERT  TVKO FROM LSS_TVKO.
    INSERT  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ENDIF.
ENDFUNCTION.
FORM CHECKSD08.
  DATA:
    LS_TVKO TYPE TVKO,
    I_DATA  TYPE  ZST_BM_SALES_SD08.
  DATA: LSS_TVKO            TYPE TVKO,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  I_DATA = GS_DATASD08.
  SELECT SINGLE
    VKORG
      FROM TVKO
      INTO CORRESPONDING FIELDS OF  LS_TVKO
      WHERE VKORG = GS_DATASD08-VKORG.

  IF SY-SUBRC IS INITIAL .
    IF  GS_DATASD08-BUKRS IS INITIAL.

    ELSE.
      GS_SD08-VKORG = GS_DATASD08-VKORG.
      GS_SD08-BUKRS = GS_DATASD08-BUKRS.
      MOVE-CORRESPONDING GS_SD08 TO LSS_TVKO.
      MOVE-CORRESPONDING GS_SD08 TO LS_TASSIGN_SD_VKORG.

      UPDATE  TVKO FROM LSS_TVKO.
      UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
    ENDIF.
  ENDIF.
ENDFORM.
