FUNCTION ZFM_BM_CS_SALES_ORG_SDD216.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD216
*"----------------------------------------------------------------------
DATA:
         LSS_TVLP TYPE TVLP.
  GS_DATASD216 = I_DATA.
  SELECT SINGLE *
    FROM TVLP
    INTO CORRESPONDING FIELDS OF GT_SD216
    WHERE PSTYV = GS_DATASD216-PSTYV.
  IF  SY-SUBRC IS INITIAL.
    GS_SD216-PSTYV = GS_DATASD216-PSTYV.
    GS_SD216-STGAP = GS_DATASD216-STGAP.
    MOVE-CORRESPONDING GS_SD216 TO LSS_TVLP.
    UPDATE TVLP FROM LSS_TVLP.
  ELSE.
    GS_SD216-PSTYV = GS_DATASD216-PSTYV.
    GS_SD216-STGAP = GS_DATASD216-STGAP.
    MOVE-CORRESPONDING GS_SD216 TO LSS_TVLP.
    INSERT TVLP FROM LSS_TVLP.
  ENDIF.
ENDFUNCTION.
