FUNCTION ZFM_BM_CS_SALES_ORG_SD37.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD37
*"----------------------------------------------------------------------
DATA: LSS_TVAP         TYPE TVAP.

  GS_DATASD37 = I_DATA.
  SELECT SINGLE
    *
      FROM TVAP
       INTO CORRESPONDING FIELDS OF  GT_SD37
      WHERE PSTYV = GS_DATASD37-PSTYV.
  IF SY-SUBRC IS INITIAL.
    GS_SD37-PSTYV = GS_DATASD37-PSTYV.
    GS_SD37-PARGR = GS_DATASD37-PARGR.
    MOVE-CORRESPONDING GS_SD37 TO LSS_TVAP.
    UPDATE  TVAP FROM LSS_TVAP.

  ELSE.
      GS_SD37-PSTYV = GS_DATASD37-PSTYV.
    GS_SD37-PARGR = GS_DATASD37-PARGR.
    MOVE-CORRESPONDING GS_SD37 TO LSS_TVAP.
   INSERT  TVAP FROM LSS_TVAP.
  ENDIF.
ENDFUNCTION.
