FUNCTION ZFM_BM_CS_SALES_ORG_SD39.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD39
*"----------------------------------------------------------------------
DATA: LSS_TVPG           TYPE TVPG,
        LS_TVPAG TYPE TVPAG.

  GS_DATASD39 = I_DATA.
  SELECT SINGLE
    TVPG~PARGR,
    TVPAG~VTEXT
      FROM TVPG
    INNER JOIN TVPAG
    ON TVPAG~PARGR = TVPG~PARGR
       INTO CORRESPONDING FIELDS OF  @GT_SD39
      WHERE TVPG~PARGR = @GS_DATASD39-PARGR.
  IF SY-SUBRC IS INITIAL.

    GS_SD39-PARGR = GS_DATASD39-PARGR.
    GS_SD39-VTEXT = GS_DATASD39-VTEXT.
    GS_SD39-PAOBJ = 'D'.
    GS_SD39-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD39 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD39 TO LS_TVPAG.

    UPDATE  TVPG FROM LSS_TVPG.
    UPDATE  TVPAG FROM LS_TVPAG.
  ELSE.
     GS_SD39-PARGR = GS_DATASD39-PARGR.
    GS_SD39-VTEXT = GS_DATASD39-VTEXT.
    GS_SD39-PAOBJ = 'D'.
    GS_SD39-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD39 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD39 TO LS_TVPAG.

    INSERT  TVPG FROM LSS_TVPG.
    INSERT  TVPAG FROM LS_TVPAG.
  ENDIF.
ENDFUNCTION.
