FUNCTION ZFM_BM_CS_SALES_ORG_SDD154.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD154
*"----------------------------------------------------------------------
DATA:
         LSS_TVAP TYPE TVAP.
  GS_DATASD154 = I_DATA.
  SELECT SINGLE *
    FROM TVAP
    INTO CORRESPONDING FIELDS OF GT_SD154
    WHERE PSTYV = GS_DATASD154-PSTYV.
  IF  SY-SUBRC IS INITIAL.
    GS_SD154-PSTYV = GS_DATASD154-PSTYV.
    GS_SD154-CMPNT = GS_DATASD154-CMPNT.
    MOVE-CORRESPONDING GS_SD154 TO LSS_TVAP.
    UPDATE TVAP FROM LSS_TVAP.
  ELSE.
   GS_SD154-PSTYV = GS_DATASD154-PSTYV.
    GS_SD154-CMPNT = GS_DATASD154-CMPNT.
    MOVE-CORRESPONDING GS_SD154 TO LSS_TVAP.
    INSERT TVAP FROM LSS_TVAP.

  ENDIF.
ENDFUNCTION.
