FUNCTION ZFM_BM_CS_SAORG_V_TVST.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_V_TVST
*"  EXPORTING
*"     REFERENCE(ET_RETURN) TYPE  BAPIRET2_T
*"----------------------------------------------------------------------

  DATA:
    LS_TVST     TYPE  TVST,
    LV_ADDR_NUM TYPE ADRC-ADDRNUMBER.
  DATA: LSS_TVST TYPE TVST,
        LS_TVSTT TYPE TVSTT.
  CLEAR:
   GT_RETURN,
   ADTEL[],
   ADFAX[],
   ADSMTP[],
   GT_TVST
   .
  GS_DATA1 = I_DATA.
  SELECT
        TVST~VSTEL,
        TVSTT~VTEXT,
        TVST~FABKL,
        TVST~ADRNR,
        TVST~VTRZT,
        TVST~ALAND,
        TVST~AZONE,
        TVST~TXNAM_ADR,
        TVST~TXNAM_KOP,
        TVST~TXNAM_FUS,
        TVST~TXNAM_GRU,
        TVST~KSCHL,
        TVSTT~SPRAS,
        TVST~ANZAL,
        TVST~VSZTP,
        TVST~NACHA,
        TVST~LAZBS,
        TVST~RIZBS,
        TVST~LAZZT,
        TVST~RIZZT,
        TVST~KOQUI,
        TVST~KOMSU,
        TVST~IMESS,
        TVST~TXNAM_SDB,
        TVST~LOADTG,
        TVST~LOADTN,
        TVST~PIPATG,
        TVST~PIPATN,
        TVST~TSTRID,
        TVST~AUTOMATIC_PICK
      FROM TVST
      LEFT JOIN TVSTT
        ON TVSTT~VSTEL = TVST~VSTEL
        AND TVSTT~SPRAS = @SY-LANGU
      INTO CORRESPONDING FIELDS OF TABLE @GT_TVST
      WHERE TVST~VSTEL = @I_DATA-VSTEL.
**  ENDSELECT.
  IF SY-SUBRC IS INITIAL.
    CLEAR
    G_MODE.
    G_MODE = '1'.
    PERFORM CHECK1 .
    ET_RETURN = GT_RETURN.
    IF ET_RETURN IS NOT INITIAL .
      RETURN.
    ENDIF.
    READ TABLE GT_TVST INTO GS_TVST INDEX 1.
    IF SY-SUBRC = 0.
      CASE  GS_TVST-ADRNR.
        WHEN '' .
          PERFORM  INSERT_ADDR1 CHANGING LV_ADDR_NUM.

          GS_TVST-ADRNR = LV_ADDR_NUM.
        WHEN OTHERS.
          PERFORM UPDATE_ADDR1 CHANGING GS_TVST.
      ENDCASE.
*    LOOP AT GT_TVKO INTO DATA(GS_TVKO) .
      GS_TVST-VSTEL = GS_DATA1-VSTEL.
      GS_TVST-VTEXT = GS_DATA1-VTEXT.
      GS_TVST-FABKL = GS_DATA1-FABKL.
*      GS_TVST-ADRNR =
      GS_TVST-VTRZT = GS_DATA1-VTRZT.
      GS_TVST-ALAND = GS_DATA1-ALAND.
      GS_TVST-AZONE = GS_DATA1-AZONE.
      GS_TVST-TXNAM_ADR = GS_DATA1-TXNAM_ADR.
      GS_TVST-TXNAM_KOP = GS_DATA1-TXNAM_KOP.
      GS_TVST-TXNAM_FUS = GS_DATA1-TXNAM_FUS.
      GS_TVST-TXNAM_GRU = GS_DATA1-TXNAM_GRU.
      GS_TVST-KSCHL = GS_DATA1-KSCHL.
      GS_TVST-ANZAL = GS_DATA1-ANZAL.
      GS_TVST-VSZTP = GS_DATA1-VSZTP.
      GS_TVST-NACHA = GS_DATA1-NACHA.
      GS_TVST-LAZBS = GS_DATA1-LAZBS.
      GS_TVST-RIZBS = GS_DATA1-RIZBS.
      GS_TVST-LAZZT = GS_DATA1-LAZZT.
      GS_TVST-RIZZT = GS_DATA1-RIZZT.
      GS_TVST-KOQUI = GS_DATA1-KOQUI.
      GS_TVST-KOMSU = GS_DATA1-KOMSU.
      GS_TVST-IMESS = GS_DATA1-IMESS.
      GS_TVST-TXNAM_SDB = GS_DATA1-TXNAM_SDB.
      GS_TVST-LOADTG = GS_DATA1-LOADTG.
      GS_TVST-LOADTN = GS_DATA1-LOADTN.
      GS_TVST-PIPATG = GS_DATA1-PIPATG.
      GS_TVST-PIPATN = GS_DATA1-PIPATN.
      GS_TVST-TSTRID = GS_DATA1-TSTRID.
      GS_TVST-AUTOMATIC_PICK = GS_DATA1-AUTOMATIC_PICK.
      GS_TVST-SPRAS = SY-LANGU.
      MOVE-CORRESPONDING GS_TVST TO LSS_TVST.
      MOVE-CORRESPONDING GS_TVST TO LS_TVSTT.

      UPDATE  TVST FROM LSS_TVST.
      UPDATE  TVSTT FROM LS_TVSTT.

*    ENDLOOP.
    ENDIF.
  ELSE.
    CLEAR
       G_MODE.
    G_MODE = '2'.
    PERFORM CHECK1.

    ET_RETURN = GT_RETURN.
    IF ET_RETURN IS NOT INITIAL .
      RETURN.
    ENDIF.
    PERFORM  INSERT_ADDR1 CHANGING LV_ADDR_NUM.
    GS_TVST-VSTEL = GS_DATA1-VSTEL.
    GS_TVST-VTEXT = GS_DATA1-VTEXT.
    GS_TVST-FABKL = GS_DATA1-FABKL.
    GS_TVST-VTRZT = GS_DATA1-VTRZT.
    GS_TVST-ALAND = GS_DATA1-ALAND.
    GS_TVST-AZONE = GS_DATA1-AZONE.
    GS_TVST-TXNAM_ADR = GS_DATA1-TXNAM_ADR.
    GS_TVST-TXNAM_KOP = GS_DATA1-TXNAM_KOP.
    GS_TVST-TXNAM_FUS = GS_DATA1-TXNAM_FUS.
    GS_TVST-TXNAM_GRU = GS_DATA1-TXNAM_GRU.
    GS_TVST-KSCHL = GS_DATA1-KSCHL.
    GS_TVST-ANZAL = GS_DATA1-ANZAL.
    GS_TVST-VSZTP = GS_DATA1-VSZTP.
    GS_TVST-NACHA = GS_DATA1-NACHA.
    GS_TVST-LAZBS = GS_DATA1-LAZBS.
    GS_TVST-RIZBS = GS_DATA1-RIZBS.
    GS_TVST-LAZZT = GS_DATA1-LAZZT.
    GS_TVST-RIZZT = GS_DATA1-RIZZT.
    GS_TVST-KOQUI = GS_DATA1-KOQUI.
    GS_TVST-KOMSU = GS_DATA1-KOMSU.
    GS_TVST-IMESS = GS_DATA1-IMESS.
    GS_TVST-TXNAM_SDB = GS_DATA1-TXNAM_SDB.
    GS_TVST-LOADTG = GS_DATA1-LOADTG.
    GS_TVST-LOADTN = GS_DATA1-LOADTN.
    GS_TVST-PIPATG = GS_DATA1-PIPATG.
    GS_TVST-PIPATN = GS_DATA1-PIPATN.
    GS_TVST-TSTRID = GS_DATA1-TSTRID.
    GS_TVST-AUTOMATIC_PICK = GS_DATA1-AUTOMATIC_PICK.
    GS_TVST-ADRNR = LV_ADDR_NUM.
    GS_TVST-SPRAS = SY-LANGU.
    MOVE-CORRESPONDING GS_TVST TO LSS_TVST.
    MOVE-CORRESPONDING GS_TVST TO LS_TVSTT.
    INSERT  TVST FROM LSS_TVST.
    INSERT  TVSTT FROM LS_TVSTT.
  ENDIF.
ENDFUNCTION.
FORM CHECK1.
  CASE G_MODE.
    WHEN '1'. " update
      PERFORM CHECK_UPDATE1.
    WHEN '2'. " insert
*      PERFORM REQUIRE.
    WHEN OTHERS.
  ENDCASE.
ENDFORM.

FORM CHECK_UPDATE1.
  DATA:
    LS_TVST TYPE TVST,
    I_DATA  TYPE  ZST_BM_SALES_V_TVST.

  I_DATA = GS_DATA1.
  SELECT SINGLE
    VSTEL
      FROM TVST
      INTO CORRESPONDING FIELDS OF  LS_TVST
      WHERE VSTEL = GS_DATA1-VSTEL.

  IF SY-SUBRC IS INITIAL .
    IF  GS_DATA1-VTEXT  IS INITIAL
       AND  GS_DATA1-TITLE_MEDI IS INITIAL
       AND  GS_DATA1-NAME1 IS INITIAL
       AND  GS_DATA1-NAME2 IS INITIAL
       AND  GS_DATA1-NAME3 IS INITIAL
       AND  GS_DATA1-NAME4 IS INITIAL
       AND  GS_DATA1-SORT1 IS INITIAL
       AND  GS_DATA1-SORT2 IS INITIAL
       AND  GS_DATA1-STR_SUPPL1 IS INITIAL
       AND  GS_DATA1-STR_SUPPL2 IS INITIAL
       AND  GS_DATA1-STR_SUPPL3 IS INITIAL
       AND  GS_DATA1-LOCATION IS INITIAL
       AND  GS_DATA1-STREET IS INITIAL
       AND  GS_DATA1-POST_CODE1 IS INITIAL
       AND  GS_DATA1-CITY1 IS INITIAL
       AND  GS_DATA1-CITY2 IS INITIAL
       AND  GS_DATA1-COUNTRY IS INITIAL
       AND  GS_DATA1-REGION IS INITIAL
       AND  GS_DATA1-TIME_ZONE IS INITIAL
       AND  GS_DATA1-PO_BOX IS INITIAL
       AND  GS_DATA1-POST_CODE2 IS INITIAL
       AND  GS_DATA1-POST_CODE3 IS INITIAL
       AND  GS_DATA1-LANGU IS INITIAL
       AND  GS_DATA1-DEFLT_COMM IS INITIAL
       AND  GS_DATA1-REMARK IS INITIAL.
    ELSE.
      LS_TVST-VSTEL = GS_DATA1-VSTEL.
      LS_TVST-FABKL = GS_DATA1-FABKL.
      LS_TVST-VTRZT = GS_DATA1-VTRZT.
      GS_TVST-ALAND = GS_DATA1-ALAND.
      LS_TVST-AZONE = GS_DATA1-AZONE.
      LS_TVST-TXNAM_ADR = GS_DATA1-TXNAM_ADR.
      LS_TVST-TXNAM_KOP = GS_DATA1-TXNAM_KOP.
      LS_TVST-TXNAM_FUS = GS_DATA1-TXNAM_FUS.
      LS_TVST-TXNAM_GRU = GS_DATA1-TXNAM_GRU.
      LS_TVST-KSCHL = GS_DATA1-KSCHL.
      LS_TVST-ANZAL = GS_DATA1-ANZAL.
      LS_TVST-VSZTP = GS_DATA1-VSZTP.
      LS_TVST-NACHA = GS_DATA1-NACHA.
      LS_TVST-LAZBS = GS_DATA1-LAZBS.
      LS_TVST-RIZBS = GS_DATA1-RIZBS.
      LS_TVST-LAZZT = GS_DATA1-LAZZT.
      LS_TVST-RIZZT = GS_DATA1-RIZZT.
      LS_TVST-KOQUI = GS_DATA1-KOQUI.
      LS_TVST-KOMSU = GS_DATA1-KOMSU.
      LS_TVST-IMESS = GS_DATA1-IMESS.
      LS_TVST-TXNAM_SDB = GS_DATA1-TXNAM_SDB.
      LS_TVST-LOADTG = GS_DATA1-LOADTG.
      LS_TVST-LOADTN = GS_DATA1-LOADTN.
      LS_TVST-PIPATG = GS_DATA1-PIPATG.
      LS_TVST-PIPATN = GS_DATA1-PIPATN.
      LS_TVST-TSTRID = GS_DATA1-TSTRID.
      LS_TVST-AUTOMATIC_PICK = GS_DATA1-AUTOMATIC_PICK.
      UPDATE  TVST FROM LS_TVST.
    ENDIF.
  ENDIF.
ENDFORM.
FORM INSERT_ADDR1 CHANGING LV_ADDR_NUM  TYPE ADRC-ADDRNUMBER.

  DATA:

    LV_ADDR1_DATA TYPE ADDR1_DATA,

    LV_ADDR_REF   TYPE ADDR_REF,

    LV_ADDR_DATA  TYPE ADDR1_DATA.

  LV_ADDR1_DATA-TITLE = GS_DATA1-TITLE_MEDI.
  LV_ADDR1_DATA-NAME1 = GS_DATA1-NAME1.
  LV_ADDR1_DATA-NAME2 = GS_DATA1-NAME2.
  LV_ADDR1_DATA-NAME3 = GS_DATA1-NAME3.
  LV_ADDR1_DATA-NAME4 = GS_DATA1-NAME4.
  LV_ADDR1_DATA-SORT1 = GS_DATA1-SORT1.
  LV_ADDR1_DATA-SORT2 = GS_DATA1-SORT2.
  LV_ADDR1_DATA-STR_SUPPL1 = GS_DATA1-STR_SUPPL1.
  LV_ADDR1_DATA-STR_SUPPL2 = GS_DATA1-STR_SUPPL2.
  LV_ADDR1_DATA-STR_SUPPL3 = GS_DATA1-STR_SUPPL3.
  LV_ADDR1_DATA-LOCATION = GS_DATA1-LOCATION.
  LV_ADDR1_DATA-STREET = GS_DATA1-STREET.
  LV_ADDR1_DATA-POST_CODE1 = GS_DATA1-POST_CODE1.
  LV_ADDR1_DATA-CITY1 = GS_DATA1-CITY1.
  LV_ADDR1_DATA-CITY2 = GS_DATA1-CITY2.
  LV_ADDR1_DATA-COUNTRY = GS_DATA1-COUNTRY.
  LV_ADDR1_DATA-REGION = GS_DATA1-REGION.
  LV_ADDR1_DATA-TIME_ZONE = GS_DATA1-TIME_ZONE.
  LV_ADDR1_DATA-PO_BOX = GS_DATA1-PO_BOX.
  LV_ADDR1_DATA-POST_CODE2 = GS_DATA1-POST_CODE2.
  LV_ADDR1_DATA-POST_CODE3 = GS_DATA1-POST_CODE3.
  LV_ADDR1_DATA-LANGU = GS_DATA1-LANGU.
  LV_ADDR1_DATA-DEFLT_COMM = GS_DATA1-DEFLT_COMM.
  LV_ADDR1_DATA-REMARK = GS_DATA1-REMARK.

  LV_ADDR_REF-ADDR_GROUP = 'CA01'.

*wa_addr_ref-owner = 'X'.

  LV_ADDR_REF-APPL_TABLE = 'ADRC'.

  LV_ADDR_REF-APPL_FIELD = 'ADDRNUMBER'.

  CALL FUNCTION 'ADDR_INSERT'
    EXPORTING
      ADDRESS_DATA    = LV_ADDR1_DATA
      ADDRESS_GROUP   = 'CA01'
      ADDRESS_HANDLE  = 'Address '
*     DATE_FROM       = '00010101'
*     LANGUAGE        = SY-LANGU
*     CHECK_EMPTY_ADDRESS = 'X'
*     CHECK_ADDRESS   = 'X'
    IMPORTING
      ADDRESS_DATA    = LV_ADDR_DATA
*     RETURNCODE      =
* TABLES
*     ERROR_TABLE     =
    EXCEPTIONS
      ADDRESS_EXISTS  = 1
      PARAMETER_ERROR = 2
      INTERNAL_ERROR  = 3
      OTHERS          = 4.

  IF SY-SUBRC <> 0.

* Implement suitable error handling here

  ENDIF.

  PERFORM ADD_TEL1 CHANGING LV_ADDR_NUM.
  PERFORM ADD_FAX1 CHANGING LV_ADDR_NUM.
  PERFORM ADD_SMTP1 CHANGING LV_ADDR_NUM.

  CALL FUNCTION 'ADDR_NUMBER_GET'
    EXPORTING
      ADDRESS_HANDLE           = 'Address '
      ADDRESS_REFERENCE        = LV_ADDR_REF
      PERSONAL_ADDRESS         = ' '
*     NUMBERRANGE_NUMBER       = '01'
*     E071K_WA                 =
*     GENERATE_TRANSPORT_ENTRIES =
*     OWNER                    = 'X'
*     TABLE_NAME               =
*     FIELD_NAME               =
*     OBJKEY                   =
    IMPORTING
      ADDRESS_NUMBER           = LV_ADDR_NUM
*     RETURNCODE_NUMBERRANGE   =
* TABLES
*     E071K_TAB                =
    EXCEPTIONS
      ADDRESS_HANDLE_NOT_EXIST = 1
      INTERNAL_ERROR           = 2
      PARAMETER_ERROR          = 3
      OTHERS                   = 4.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  CALL FUNCTION 'ADDR_MEMORY_SAVE'
    EXPORTING
      EXECUTE_IN_UPDATE_TASK = ' '
    EXCEPTIONS
      ADDRESS_NUMBER_MISSING = 1
      PERSON_NUMBER_MISSING  = 2
      INTERNAL_ERROR         = 3
      DATABASE_ERROR         = 4
      REFERENCE_MISSING      = 5
      OTHERS                 = 6.

  IF SY-SUBRC <> 0.

    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO

    WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.

  ENDIF.
  PERFORM SET_UPDATE_FLAG.
  COMMIT WORK AND WAIT.

  CALL FUNCTION 'ADDR_MEMORY_CLEAR'
    EXPORTING
      FORCE              = ' '
    EXCEPTIONS
      UNSAVED_DATA_EXIST = 1
      INTERNAL_ERROR     = 2
      OTHERS             = 3.

  IF SY-SUBRC <> 0.

    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO

    WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.

  ENDIF.
ENDFORM.
FORM UPDATE_ADDR1 CHANGING LPS_TVST TYPE GTY_TVST.
  DATA:
    LV_ADDR_NUM       TYPE ADRC-ADDRNUMBER,
    LV_ADDR1_DATA     TYPE ADDR1_DATA,
    LV_RETURNCODE     TYPE AD_RETCODE,
    LS_ADDR1_SEL      LIKE  ADDR1_SEL,
    LT_ADDR_ERROR     TYPE TABLE OF ADDR_ERROR,
    LV_ADDR1_OLD_VERS TYPE TABLE OF ADDR_VERS,
    LS_AD1_FLAGS      LIKE   AD1_FLAGS,
    LV_ADDR_GET       LIKE  ADDR1_VAL.

  LV_ADDR_NUM = LPS_TVST-ADRNR.
  LS_ADDR1_SEL-ADDRNUMBER = LV_ADDR_NUM.

  CALL FUNCTION 'ADDR_GET'
    EXPORTING
      ADDRESS_SELECTION       = LS_ADDR1_SEL
    IMPORTING
      ADDRESS_VALUE           = LV_ADDR_GET
      ADDRESS_ADDITIONAL_INFO = LS_AD1_FLAGS            "*1181i
*     returncode              = returncode              "*963d
      RETURNCODE              = LV_RETURNCODE           "*963i
    TABLES
      ERROR_TABLE             = E_TABLE
      VERSIONS                = LV_ADDR1_OLD_VERS
    EXCEPTIONS
      PARAMETER_ERROR         = 1
      ADDRESS_NOT_EXIST       = 2
      VERSION_NOT_EXIST       = 3
      INTERNAL_ERROR          = 4
      OTHERS                  = 5.
  DATA:
    LS_TVST TYPE TVST,
    I_DATA  TYPE  ZST_BM_SALES_V_TVST.

  MOVE-CORRESPONDING LV_ADDR_GET TO LV_ADDR1_DATA.

  I_DATA = GS_DATA1.
  SELECT SINGLE
    VSTEL
      FROM TVST
      INTO CORRESPONDING FIELDS OF  LS_TVST
      WHERE VSTEL = GS_DATA1-VSTEL.

  IF SY-SUBRC IS INITIAL .

    LV_ADDR1_DATA-TITLE = GS_DATA1-TITLE_MEDI .
    LV_ADDR1_DATA-NAME1 = GS_DATA1-NAME1 .
    LV_ADDR1_DATA-NAME2 = GS_DATA1-NAME2 .
    LV_ADDR1_DATA-NAME3 = GS_DATA1-NAME3 .
    LV_ADDR1_DATA-NAME4 = GS_DATA1-NAME4.
    LV_ADDR1_DATA-SORT1 = GS_DATA1-SORT1 .
    LV_ADDR1_DATA-SORT2 = GS_DATA1-SORT2 .
    LV_ADDR1_DATA-STR_SUPPL1 = GS_DATA1-STR_SUPPL1 .
    LV_ADDR1_DATA-STR_SUPPL2 = GS_DATA1-STR_SUPPL2 .
    LV_ADDR1_DATA-STR_SUPPL3 = GS_DATA1-STR_SUPPL3 .
    LV_ADDR1_DATA-LOCATION = GS_DATA1-LOCATION .
    LV_ADDR1_DATA-STREET = GS_DATA1-STREET .
    LV_ADDR1_DATA-POST_CODE1 = GS_DATA1-POST_CODE1 .
    LV_ADDR1_DATA-CITY1 = GS_DATA1-CITY1 .
    LV_ADDR1_DATA-CITY2 = GS_DATA1-CITY2 .
    LV_ADDR1_DATA-COUNTRY = GS_DATA1-COUNTRY .
    LV_ADDR1_DATA-REGION = GS_DATA1-REGION .
    LV_ADDR1_DATA-TIME_ZONE = GS_DATA1-TIME_ZONE .
    LV_ADDR1_DATA-PO_BOX = GS_DATA1-PO_BOX .
    LV_ADDR1_DATA-POST_CODE2 = GS_DATA1-POST_CODE2 .
    LV_ADDR1_DATA-POST_CODE3 = GS_DATA1-POST_CODE3 .
    LV_ADDR1_DATA-LANGU = GS_DATA1-LANGU .
    LV_ADDR1_DATA-DEFLT_COMM = GS_DATA1-DEFLT_COMM .
    LV_ADDR1_DATA-REMARK = GS_DATA1-REMARK .
  ENDIF.

  CALL FUNCTION 'ADDR_UPDATE'
    EXPORTING
      ADDRESS_DATA      = LV_ADDR1_DATA
      ADDRESS_NUMBER    = LV_ADDR_NUM
*     DATE_FROM         = '00010101'
*     LANGUAGE          = SY-LANGU
*     NATION            = ' '
*     CHECK_EMPTY_ADDRESS        = 'X'
*     CHECK_ADDRESS     = 'X'
*     CHECK_OTHER_VERSIONS       = 'X'
*     BLK_EXCPT         =
    IMPORTING
*     ADDRESS_DATA      =
      RETURNCODE        = LV_RETURNCODE
*     DATA_HAS_CHANGED  =
    TABLES
      ERROR_TABLE       = LT_ADDR_ERROR
    EXCEPTIONS
      ADDRESS_NOT_EXIST = 1
      PARAMETER_ERROR   = 2
      VERSION_NOT_EXIST = 3
      INTERNAL_ERROR    = 4
      ADDRESS_BLOCKED   = 5
      OTHERS            = 6.
  IF SY-SUBRC <> 0.

    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO

    WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.

  ENDIF.

  PERFORM ADD_TEL1 CHANGING LV_ADDR_NUM.
  PERFORM ADD_FAX1 CHANGING LV_ADDR_NUM.
  PERFORM ADD_SMTP1 CHANGING LV_ADDR_NUM.

  CALL FUNCTION 'ADDR_MEMORY_SAVE'
    EXPORTING
      EXECUTE_IN_UPDATE_TASK = ' '
    EXCEPTIONS
      ADDRESS_NUMBER_MISSING = 1
      PERSON_NUMBER_MISSING  = 2
      INTERNAL_ERROR         = 3
      DATABASE_ERROR         = 4
      REFERENCE_MISSING      = 5
      OTHERS                 = 6.

  IF SY-SUBRC <> 0.

    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO

    WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.

  ENDIF.
  PERFORM SET_UPDATE_FLAG.
  CALL FUNCTION 'ADDR_MEMORY_CLEAR'
    EXPORTING
      FORCE              = ' '
    EXCEPTIONS
      UNSAVED_DATA_EXIST = 1
      INTERNAL_ERROR     = 2
      OTHERS             = 3.

  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
    WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
ENDFORM.

FORM ADD_TEL1 CHANGING LV_ADDR_NUM TYPE ADRC-ADDRNUMBER .
  DATA:
    LV_TABLE  LIKE SZAD_FIELD-TABLE_TYPE,
    LV_INDEX  TYPE INT4,
    LV_HANDLE TYPE SZAD_FIELD-HANDLE.
  DATA: LV_RETURNCODE TYPE AD_RETCODE.

  SELECT *
    FROM ADR2
    INTO TABLE @DATA(LT_ADR2)
    WHERE ADDRNUMBER = @LV_ADDR_NUM.

  IF G_MODE = '1'.
    LV_INDEX += 1.
    ADTEL-CONSNUMBER = LV_INDEX.
  ENDIF.

  ADTEL-TEL_NUMBER = GS_DATA1-TEL_NUMBER.
  ADTEL-TEL_EXTENS = GS_DATA1-TEL_EXTENS.
  ADTEL-COUNTRY    = GS_DATA1-COUNTRY.
  ADTEL-FLGDEFAULT = 'X'.
  ADTEL-HOME_FLAG = 'X'.
  ADTEL-R3_USER    = '1'.
  IF G_MODE = '1'.
    READ TABLE LT_ADR2 TRANSPORTING NO FIELDS
      WITH KEY ADDRNUMBER = LV_ADDR_NUM
               R3_USER    = '1'.
    IF SY-SUBRC IS INITIAL.
      ADTEL-UPDATEFLAG = 'U'.
      IF GS_DATA1-TEL_NUMBER IS INITIAL.
        ADTEL-UPDATEFLAG = 'D'.
      ENDIF.
    ELSEIF GS_DATA1-TEL_NUMBER IS NOT INITIAL.
      ADTEL-UPDATEFLAG = 'I'.
    ENDIF.
  ELSEIF GS_DATA1-TEL_NUMBER IS NOT INITIAL.
    ADTEL-UPDATEFLAG = 'I'.
  ENDIF.

*  ADTEL-TEL_EXTENS = GS_DATA-TEL_EXTENS.
  APPEND ADTEL.

  IF G_MODE = '1'.
    LV_INDEX += 1.
    ADTEL-CONSNUMBER = LV_INDEX.
  ENDIF.
  ADTEL-TEL_NUMBER = GS_DATA1-MOB_NUMBER.
  ADTEL-TEL_EXTENS = GS_DATA1-MOB_NUMBER.
  ADTEL-COUNTRY    = GS_DATA1-COUNTRY.
  ADTEL-FLGDEFAULT = ''.
  ADTEL-HOME_FLAG = ''.
  ADTEL-R3_USER    = '3'.
  IF G_MODE = '1'.

    READ TABLE LT_ADR2 TRANSPORTING NO FIELDS
      WITH KEY ADDRNUMBER = LV_ADDR_NUM
               R3_USER    = '3'.
    IF SY-SUBRC IS INITIAL.
      ADTEL-UPDATEFLAG = 'U'.
      IF GS_DATA1-MOB_NUMBER IS INITIAL.
        ADTEL-UPDATEFLAG = 'D'.
      ENDIF.
    ELSEIF GS_DATA1-MOB_NUMBER IS NOT INITIAL.
      ADTEL-UPDATEFLAG = 'I'.
    ENDIF.
  ELSEIF GS_DATA1-MOB_NUMBER IS NOT INITIAL.
    ADTEL-UPDATEFLAG = 'I'.
    LV_HANDLE = 'Address'.
  ENDIF.
  APPEND ADTEL.

  LV_TABLE = 'ADTEL'.
  CALL FUNCTION 'ADDR_COMM_MAINTAIN'
    EXPORTING
      ADDRESS_NUMBER    = LV_ADDR_NUM
      ADDRESS_HANDLE    = LV_HANDLE
*     DATE_FROM         = '00010101'
*     LANGUAGE          = SY-LANGU
      TABLE_TYPE        = LV_TABLE
*     SUBSTITUTE_ALL_COMM_DATA             = ' '
*     ACCEPT_TELNR_CALL = ' '
*     CONSIDER_CONSNUMBER_FOR_INSERT       = ' '
*     CHECK_ADDRESS     = 'X'
*     IV_TIME_DEPENDENCE                   = ' '
*     IV_CONSIDER_ADRCOMC_FOR_INSERT       = 'X'
*     BLK_EXCPT         =
    IMPORTING
      RETURNCODE        = LV_RETURNCODE
    TABLES
      COMM_TABLE        = ADTEL
      ERROR_TABLE       = E_TABLE
*     COMM_TABLE_OUT    =
*     IT_USAGE          =
*     IT_USAGE_UUID     =
*     ET_USAGE_OUT      =
*     ET_USAGE_UUID_OUT =
*     ET_CREATED_USAGE_UUID                =
    EXCEPTIONS
      PARAMETER_ERROR   = 1
      ADDRESS_NOT_EXIST = 2
      INTERNAL_ERROR    = 3
      ADDRESS_BLOCKED   = 4
      OTHERS            = 5.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  COMMIT WORK AND WAIT.
ENDFORM.

FORM ADD_FAX1 CHANGING LV_ADDR_NUM TYPE ADRC-ADDRNUMBER .
  DATA:
    LV_TABLE  LIKE SZAD_FIELD-TABLE_TYPE,
    LV_INDEX  TYPE INT4,
    LV_HANDLE TYPE SZAD_FIELD-HANDLE.
  DATA: LV_RETURNCODE TYPE AD_RETCODE.

  SELECT *
    FROM ADR3
    INTO TABLE @DATA(LT_ADR3)
    WHERE ADDRNUMBER = @LV_ADDR_NUM.
  IF G_MODE = '1'.
    LV_INDEX += 1.
    ADFAX-CONSNUMBER = LV_INDEX.
  ENDIF.

  ADFAX-FAX_NUMBER = GS_DATA1-FAX_NUMBER.
  ADFAX-FAX_EXTENS = GS_DATA1-FAX_EXTENS.
  ADFAX-COUNTRY    = GS_DATA1-COUNTRY.
  ADFAX-FLGDEFAULT = 'X'.
  ADFAX-HOME_FLAG = 'X'.
  ADFAX-R3_USER    = '1'.
  IF G_MODE = '1'.
    READ TABLE LT_ADR3 TRANSPORTING NO FIELDS
      WITH KEY ADDRNUMBER = LV_ADDR_NUM.
    IF SY-SUBRC IS INITIAL.
      ADTEL-UPDATEFLAG = 'U'.
      IF GS_DATA1-FAX_NUMBER IS INITIAL.
        ADTEL-UPDATEFLAG = 'D'.
      ENDIF.
    ELSEIF GS_DATA1-FAX_NUMBER IS NOT INITIAL.
      ADTEL-UPDATEFLAG = 'I'.
    ENDIF.
  ELSEIF GS_DATA1-FAX_NUMBER IS NOT INITIAL.
    ADFAX-UPDATEFLAG = 'I'.
    LV_HANDLE = 'Address'.
  ENDIF.
*  ADTEL-TEL_EXTENS = GS_DATA-TEL_EXTENS.
  APPEND ADFAX.

  LV_TABLE = 'ADFAX'.
  CALL FUNCTION 'ADDR_COMM_MAINTAIN'
    EXPORTING
      ADDRESS_HANDLE    = LV_HANDLE
      ADDRESS_NUMBER    = LV_ADDR_NUM
*     DATE_FROM         = '00010101'
*     LANGUAGE          = SY-LANGU
      TABLE_TYPE        = LV_TABLE
*     SUBSTITUTE_ALL_COMM_DATA             = ' '
*     ACCEPT_TELNR_CALL = ' '
*     CONSIDER_CONSNUMBER_FOR_INSERT       = ' '
*     CHECK_ADDRESS     = 'X'
*     IV_TIME_DEPENDENCE                   = ' '
*     IV_CONSIDER_ADRCOMC_FOR_INSERT       = 'X'
*     BLK_EXCPT         =
    IMPORTING
      RETURNCODE        = LV_RETURNCODE
    TABLES
      COMM_TABLE        = ADFAX
      ERROR_TABLE       = E_TABLE
*     COMM_TABLE_OUT    =
*     IT_USAGE          =
*     IT_USAGE_UUID     =
*     ET_USAGE_OUT      =
*     ET_USAGE_UUID_OUT =
*     ET_CREATED_USAGE_UUID                =
    EXCEPTIONS
      PARAMETER_ERROR   = 1
      ADDRESS_NOT_EXIST = 2
      INTERNAL_ERROR    = 3
      ADDRESS_BLOCKED   = 4
      OTHERS            = 5.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.
ENDFORM.
FORM ADD_SMTP1 CHANGING LV_ADDR_NUM TYPE ADRC-ADDRNUMBER.
  DATA:
    LV_TABLE  LIKE SZAD_FIELD-TABLE_TYPE,
    LV_INDEX  TYPE INT4,
    LV_HANDLE TYPE SZAD_FIELD-HANDLE.
  DATA: LV_RETURNCODE TYPE AD_RETCODE.
  SELECT *
     FROM ADR6
     INTO TABLE @DATA(LT_ADR6)
     WHERE ADDRNUMBER = @LV_ADDR_NUM.
  IF G_MODE = '1'.
    LV_INDEX += 1.
    ADSMTP-CONSNUMBER = LV_INDEX.
  ENDIF.

  ADSMTP-SMTP_ADDR = GS_DATA1-SMTP_ADDR.
*  ADSMTP-SMTP_SRCH = GS_DATA-SMTP_SRCH.
*  ADSMTP-COUNTRY    = GS_DATA-LAND1.
  ADSMTP-FLGDEFAULT = 'X'.
  ADSMTP-HOME_FLAG = 'X'.
  ADSMTP-R3_USER    = '1'.
  IF G_MODE = '1'.
    READ TABLE LT_ADR6 TRANSPORTING NO FIELDS
       WITH KEY ADDRNUMBER = LV_ADDR_NUM.
    IF SY-SUBRC IS INITIAL.
      ADTEL-UPDATEFLAG = 'U'.
      IF GS_DATA1-SMTP_ADDR IS INITIAL.
        ADTEL-UPDATEFLAG = 'D'.
      ENDIF.
    ELSEIF GS_DATA1-SMTP_ADDR IS NOT INITIAL.
      ADTEL-UPDATEFLAG = 'I'.
    ENDIF.
  ELSEIF GS_DATA1-SMTP_ADDR IS NOT INITIAL.
    ADSMTP-UPDATEFLAG = 'I'.
    LV_HANDLE = 'Address'.
  ENDIF.
*  ADTEL-TEL_EXTENS = GS_DATA-TEL_EXTENS.
  APPEND ADSMTP.

  LV_TABLE = 'ADSMTP'.
  CALL FUNCTION 'ADDR_COMM_MAINTAIN'
    EXPORTING
      ADDRESS_HANDLE    = LV_HANDLE
      ADDRESS_NUMBER    = LV_ADDR_NUM
*     DATE_FROM         = '00010101'
*     LANGUAGE          = SY-LANGU
      TABLE_TYPE        = LV_TABLE
*     SUBSTITUTE_ALL_COMM_DATA             = ' '
*     ACCEPT_TELNR_CALL = ' '
*     CONSIDER_CONSNUMBER_FOR_INSERT       = ' '
*     CHECK_ADDRESS     = 'X'
*     IV_TIME_DEPENDENCE                   = ' '
*     IV_CONSIDER_ADRCOMC_FOR_INSERT       = 'X'
*     BLK_EXCPT         =
    IMPORTING
      RETURNCODE        = LV_RETURNCODE
    TABLES
      COMM_TABLE        = ADSMTP
      ERROR_TABLE       = E_TABLE
*     COMM_TABLE_OUT    =
*     IT_USAGE          =
*     IT_USAGE_UUID     =
*     ET_USAGE_OUT      =
*     ET_USAGE_UUID_OUT =
*     ET_CREATED_USAGE_UUID                =
    EXCEPTIONS
      PARAMETER_ERROR   = 1
      ADDRESS_NOT_EXIST = 2
      INTERNAL_ERROR    = 3
      ADDRESS_BLOCKED   = 4
      OTHERS            = 5.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.
ENDFORM.
FORM SET_UPDATE_FLAG.

  IF GF_FLAG_ADDRESS_CHANGE NE SPACE.
    <STATUS>-UPD_FLAG = 'X'.
  ENDIF.

ENDFORM.                    "set_udpate_flag
