FUNCTION ZFM_BM_CS_SALES_ORG_SD100.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD100
*"----------------------------------------------------------------------
DATA: LSS_TVEP         TYPE TVEP.

  GS_DATASD100 = I_DATA.
  SELECT SINGLE
    *
      FROM TVEP
       INTO CORRESPONDING FIELDS OF  GT_SD100
      WHERE ETTYP = GS_DATASD100-ETTYP .
  IF SY-SUBRC IS INITIAL.
    GS_SD100-ETTYP = GS_DATASD100-ETTYP.
    GS_SD100-FEHGR = GS_DATASD100-FEHGR.

    MOVE-CORRESPONDING GS_SD100 TO LSS_TVEP.
    UPDATE  TVEP FROM LSS_TVEP.

  ELSE.
    GS_SD100-ETTYP = GS_DATASD100-ETTYP.
    GS_SD100-FEHGR = GS_DATASD100-FEHGR.

    MOVE-CORRESPONDING GS_SD100 TO LSS_TVEP.
    INSERT  TVEP FROM LSS_TVEP.
  ENDIF.
ENDFUNCTION.
