FUNCTION ZFM_BM_CS_SALES_ORG_SD84.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD84
*"----------------------------------------------------------------------
  DATA: LSS_TVAK           TYPE TVAK.

  GS_DATASD84 = I_DATA.
  SELECT SINGLE
    *
      FROM TVAK
       INTO CORRESPONDING FIELDS OF  GT_SD84
      WHERE AUART = GS_DATASD84-AUART .
  IF SY-SUBRC IS INITIAL.
    GS_SD84-AUART = GS_DATASD84-AUART .
    GS_SD84-KALVG = GS_DATASD84-KALVG.
    MOVE-CORRESPONDING GS_SD84 TO LSS_TVAK.
    UPDATE  TVAK FROM LSS_TVAK.

  ELSE.
    GS_SD84-AUART = GS_DATASD84-AUART .
    GS_SD84-KALVG = GS_DATASD84-KALVG.
    MOVE-CORRESPONDING GS_SD84 TO LSS_TVAK.
    INSERT  TVAK FROM LSS_TVAK.
  ENDIF.
ENDFUNCTION.
