FUNCTION ZFM_BM_CS_SALES_ORG_SD16.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD16
*"----------------------------------------------------------------------

  DATA: LSS_TVKBZ            TYPE TVKBZ,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  GS_DATASD16 = I_DATA.
  SELECT SINGLE
    TVKBZ~VKORG,
    TVKBZ~VTWEG,
    TVKBZ~SPART,
    TVKBZ~VKBUR,
    TASSIGN_SD_VKORG~STATUS_ASSIGN_SD,
    TVKBZ~HIDE
      FROM TVKBZ
    INNER JOIN TASSIGN_SD_VKORG
    ON TASSIGN_SD_VKORG~VKORG = TVKBZ~VKORG
       INTO CORRESPONDING FIELDS OF  @GT_SD16
      WHERE TVKBZ~VKORG = @GS_DATASD16-VKORG
    AND TVKBZ~VTWEG = @GS_DATASD16-VTWEG
    AND TVKBZ~SPART = @GS_DATASD16-SPART
    AND TVKBZ~VKBUR = @GS_DATASD16-VKBUR.
  IF SY-SUBRC IS INITIAL.
    PERFORM CHECKSD16.
    GS_SD16-VKORG = GS_DATASD16-VKORG.
    GS_SD16-VTWEG = GS_DATASD16-VTWEG.
    GS_SD16-SPART = GS_DATASD16-SPART.
    GS_SD16-VKBUR = GS_DATASD16-VKBUR.
    GS_SD16-HIDE = GS_DATASD16-HIDE.
    MOVE-CORRESPONDING GS_SD16 TO LSS_TVKBZ.
    MOVE-CORRESPONDING GS_SD16 TO LS_TASSIGN_SD_VKORG.

    UPDATE  TVKBZ FROM LSS_TVKBZ.
    UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ELSE.
    GS_SD16-VKORG = GS_DATASD16-VKORG.
    GS_SD16-VTWEG = GS_DATASD16-VTWEG.
    GS_SD16-SPART = GS_DATASD16-SPART.
    GS_SD16-VKBUR = GS_DATASD16-VKBUR.
    GS_SD16-HIDE = GS_DATASD16-HIDE.
    MOVE-CORRESPONDING GS_SD16 TO LSS_TVKBZ.
    MOVE-CORRESPONDING GS_SD16 TO LS_TASSIGN_SD_VKORG.

    INSERT  TVKBZ FROM LSS_TVKBZ.
    INSERT  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ENDIF.
ENDFUNCTION.
FORM CHECKSD16.
  DATA:
    LS_TVKBZ TYPE TVKBZ,
    I_DATA  TYPE  ZST_BM_SALES_SD16.
  DATA: LSS_TVKBZ           TYPE TVKBZ,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  I_DATA = GS_DATASD16.
  SELECT SINGLE
    VKORG
      FROM TVKBZ
      INTO CORRESPONDING FIELDS OF  LS_TVKBZ
      WHERE VKORG = GS_DATASD16-VKORG
     AND TVKBZ~VTWEG = GS_DATASD16-VTWEG
    AND TVKBZ~SPART = GS_DATASD16-SPART
    AND TVKBZ~VKBUR = GS_DATASD16-VKBUR.

  IF SY-SUBRC IS INITIAL .
    IF  GS_DATASD16-VTWEG  IS INITIAL
      AND GS_DATASD16-SPART IS INITIAL
      AND GS_DATASD16-VKBUR IS INITIAL
      AND GS_DATASD16-HIDE IS INITIAL.
    ELSE.
     GS_SD16-VKORG = GS_DATASD16-VKORG.
    GS_SD16-VTWEG = GS_DATASD16-VTWEG.
    GS_SD16-SPART = GS_DATASD16-SPART.
    GS_SD16-VKBUR = GS_DATASD16-VKBUR.
    GS_SD16-HIDE = GS_DATASD16-HIDE.
    MOVE-CORRESPONDING GS_SD16 TO LSS_TVKBZ.
    MOVE-CORRESPONDING GS_SD16 TO LS_TASSIGN_SD_VKORG.

    UPDATE  TVKBZ FROM LSS_TVKBZ.
    UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
    ENDIF.
  ENDIF.
ENDFORM.
