FUNCTION ZFM_BM_CS_SALES_ORG_SD75.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD75
*"----------------------------------------------------------------------
 DATA: LSS_T682I TYPE T682I.

  GS_DATASD75 = I_DATA.
  SELECT SINGLE
    *
      FROM T682I

       INTO CORRESPONDING FIELDS OF  @GT_SD75
      WHERE T682I~KVEWE = @GS_DATASD75-KVEWE
    AND KAPPL = @GS_DATASD75-KAPPL
    AND KOZGF = @GS_DATASD75-KOZGF
    AND KOLNR = @GS_DATASD75-KOLNR.
  IF SY-SUBRC IS INITIAL.
    GS_SD75-KVEWE = 'C'.
    GS_SD75-KAPPL = 'VB'.
    GS_SD75-KOZGF = GS_DATASD75-KOZGF.
    GS_SD75-KOLNR = GS_DATASD75-KOLNR.
    GS_SD75-KOTABNR = GS_DATASD75-KOTABNR.
    GS_SD75-KOBED = GS_DATASD75-KOBED.
    GS_SD75-KZEXL = GS_DATASD75-KZEXL.
    GS_SD75-KKOPF = 'X'.
    GS_SD75-GZUGR = GS_DATASD75-GZUGR.

    MOVE-CORRESPONDING GS_SD75 TO LSS_T682I.
    UPDATE  T682I FROM LSS_T682I.

  ELSE.
     GS_SD75-KVEWE = 'C'.
    GS_SD75-KAPPL = 'VB'.
    GS_SD75-KOZGF = GS_DATASD75-KOZGF.
    GS_SD75-KOLNR = GS_DATASD75-KOLNR.
    GS_SD75-KOTABNR = GS_DATASD75-KOTABNR.
    GS_SD75-KOBED = GS_DATASD75-KOBED.
    GS_SD75-KZEXL = GS_DATASD75-KZEXL.
    GS_SD75-KKOPF = 'X'.
    GS_SD75-GZUGR = GS_DATASD75-GZUGR.

    MOVE-CORRESPONDING GS_SD75 TO LSS_T682I.
    INSERT  T682I FROM LSS_T682I.
  ENDIF.
ENDFUNCTION.
