FUNCTION ZFM_BM_CS_SALES_ORG_SD66.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD66
*"----------------------------------------------------------------------
  DATA: LSS_T682I TYPE T682I.

  GS_DATASD66 = I_DATA.
  SELECT SINGLE
    *
      FROM T682I

       INTO CORRESPONDING FIELDS OF  @GT_SD66
      WHERE T682I~KVEWE = @GS_DATASD66-KVEWE
    AND KAPPL = @GS_DATASD66-KAPPL
    AND KOZGF = @GS_DATASD66-KOZGF
    AND KOLNR = @GS_DATASD66-KOLNR.
  IF SY-SUBRC IS INITIAL.
    GS_SD66-KVEWE = 'C'.
    GS_SD66-KAPPL = 'V'.
    GS_SD66-KOZGF = GS_DATASD66-KOZGF.
    GS_SD66-KOLNR = GS_DATASD66-KOLNR.
    GS_SD66-KOTABNR = GS_DATASD66-KOTABNR.
    GS_SD66-KOBED = GS_DATASD66-KOBED.
    GS_SD66-KZEXL = GS_DATASD66-KZEXL.
    GS_SD66-KKOPF = GS_DATASD66-KKOPF.
    GS_SD66-GZUGR = GS_DATASD66-GZUGR.

    MOVE-CORRESPONDING GS_SD66 TO LSS_T682I.
    UPDATE  T682I FROM LSS_T682I.

  ELSE.
    GS_SD66-KVEWE = 'C'.
    GS_SD66-KAPPL = 'V'.
    GS_SD66-KOZGF = GS_DATASD66-KOZGF.
    GS_SD66-KOLNR = GS_DATASD66-KOLNR.
    GS_SD66-KOTABNR = GS_DATASD66-KOTABNR.
    GS_SD66-KOBED = GS_DATASD66-KOBED.
    GS_SD66-KZEXL = GS_DATASD66-KZEXL.
    GS_SD66-KKOPF = GS_DATASD66-KKOPF.
    GS_SD66-GZUGR = GS_DATASD66-GZUGR.

    MOVE-CORRESPONDING GS_SD66 TO LSS_T682I.
    INSERT  T682I FROM LSS_T682I.
  ENDIF.
ENDFUNCTION.
