FUNCTION ZFM_BM_CS_SALES_ORG_SD54 .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD55
*"----------------------------------------------------------------------

 DATA: LSS_TVFK        TYPE TVFK.

  GS_DATASD55 = I_DATA.
  SELECT SINGLE
    *
      FROM TVFK
       INTO CORRESPONDING FIELDS OF  GT_SD55
      WHERE FKART = GS_DATASD55-FKART.
  IF SY-SUBRC IS INITIAL.
    GS_SD55-FKART = GS_DATASD55-FKART.
    GS_SD55-PARGP = GS_DATASD55-PARGP.
    MOVE-CORRESPONDING GS_SD55 TO LSS_TVFK.
    UPDATE  TVFK FROM LSS_TVFK.

  ELSE.
    GS_SD55-FKART = GS_DATASD55-FKART.
    GS_SD55-PARGP = GS_DATASD55-PARGP.
    MOVE-CORRESPONDING GS_SD55 TO LSS_TVFK.
    INSERT  TVFK FROM LSS_TVFK.
  ENDIF.
ENDFUNCTION.
