FUNCTION ZFM_BM_CS_SALES_ORG_SD60.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD60
*"----------------------------------------------------------------------
  DATA: LSS_T134G       TYPE T134G.

  GS_DATASD60 = I_DATA.
  SELECT SINGLE
    *
      FROM T134G
       INTO CORRESPONDING FIELDS OF  GT_SD60
      WHERE WERKS = GS_DATASD60-WERKS
    AND SPART = GS_DATASD60-SPART.
  IF SY-SUBRC IS INITIAL.
    GS_SD60-WERKS = GS_DATASD60-WERKS.
    GS_SD60-SPART = GS_DATASD60-SPART.
    GS_SD60-GSBER = GS_DATASD60-GSBER.
    MOVE-CORRESPONDING GS_SD60 TO LSS_T134G.
    UPDATE  T134G FROM LSS_T134G.

  ELSE.
    GS_SD60-WERKS = GS_DATASD60-WERKS.
    GS_SD60-SPART = GS_DATASD60-SPART.
    GS_SD60-GSBER = GS_DATASD60-GSBER.
    MOVE-CORRESPONDING GS_SD60 TO LSS_T134G.
    INSERT  T134G FROM LSS_T134G.
  ENDIF.
ENDFUNCTION.
