FUNCTION ZFM_BM_CS_SALES_ORG_SDD202.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD202
*"----------------------------------------------------------------------
  DATA:
           LSS_TVFCSF TYPE TVFCSF.
  GS_DATASD202 = I_DATA.
  SELECT SINGLE *
    FROM TVFCSF
    INTO CORRESPONDING FIELDS OF GT_SD202
    WHERE TPLST = GS_DATASD202-TPLST
    AND FCGRP = GS_DATASD202-FCGRP
    AND DLGRP = GS_DATASD202-DLGRP
    AND VSGRP = GS_DATASD202-VSGRP.
  IF  SY-SUBRC IS INITIAL.
    GS_SD202-TPLST = GS_DATASD202-TPLST.
    GS_SD202-FCGRP = GS_DATASD202-FCGRP.
    GS_SD202-DLGRP = GS_DATASD202-DLGRP.
    GS_SD202-VSGRP = GS_DATASD202-VSGRP.
    GS_SD202-KALSM = GS_DATASD202-KALSM.
    MOVE-CORRESPONDING GS_SD202 TO LSS_TVFCSF.
    UPDATE TVFCSF FROM LSS_TVFCSF.
  ELSE.
    GS_SD202-TPLST = GS_DATASD202-TPLST.
    GS_SD202-FCGRP = GS_DATASD202-FCGRP.
    GS_SD202-DLGRP = GS_DATASD202-DLGRP.
    GS_SD202-VSGRP = GS_DATASD202-VSGRP.
    GS_SD202-KALSM = GS_DATASD202-KALSM.
    MOVE-CORRESPONDING GS_SD202 TO LSS_TVFCSF.
    INSERT TVFCSF FROM LSS_TVFCSF.
  ENDIF.
ENDFUNCTION.
