FUNCTION ZFM_BM_CS_SALES_ORG_SD15.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD15
*"----------------------------------------------------------------------
  DATA: LSS_T001       TYPE T001.

  GS_DATASD15 = I_DATA.
  SELECT SINGLE
    *
      FROM T001
       INTO CORRESPONDING FIELDS OF  GT_SD15
      WHERE BUKRS = GS_DATASD15-BUKRS.
  IF SY-SUBRC IS INITIAL.
    GS_SD15-BUKRS = GS_DATASD15-BUKRS.
    GS_SD15-BUTXT = GS_DATASD15-BUTXT.
    GS_SD15-ORT01 = GS_DATASD15-ORT01.
    GS_SD15-KKBER = GS_DATASD15-KKBER.
    GS_SD15-XKKBI = GS_DATASD15-XKKBI.
    MOVE-CORRESPONDING GS_SD15 TO LSS_T001.
    UPDATE  T001 FROM LSS_T001.

  ELSE.
    GS_SD15-BUKRS = GS_DATASD15-BUKRS.
    GS_SD15-BUTXT = GS_DATASD15-BUTXT.
    GS_SD15-ORT01 = GS_DATASD15-ORT01.
    GS_SD15-KKBER = GS_DATASD15-KKBER.
    GS_SD15-XKKBI = GS_DATASD15-XKKBI.
    MOVE-CORRESPONDING GS_SD15 TO LSS_T001.
    INSERT  T001 FROM LSS_T001.
  ENDIF.
ENDFUNCTION.
