*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVI_BM_CSTR_C...................................*
FORM GET_DATA_ZVI_BM_CSTR_C.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTB_BM_CSTR_C WHERE
(VIM_WHERETAB) .
    CLEAR ZVI_BM_CSTR_C .
ZVI_BM_CSTR_C-MANDT =
ZTB_BM_CSTR_C-MANDT .
ZVI_BM_CSTR_C-MODLID =
ZTB_BM_CSTR_C-MODLID .
ZVI_BM_CSTR_C-CSFUNC =
ZTB_BM_CSTR_C-CSFUNC .
ZVI_BM_CSTR_C-TCODE =
ZTB_BM_CSTR_C-TCODE .
ZVI_BM_CSTR_C-VIEWNAME =
ZTB_BM_CSTR_C-VIEWNAME .
ZVI_BM_CSTR_C-VCL_NAME =
ZTB_BM_CSTR_C-VCL_NAME .
ZVI_BM_CSTR_C-DESCR =
ZTB_BM_CSTR_C-DESCR .
    SELECT SINGLE * FROM ZTB_BM_CSTR_M WHERE
MODLID = ZTB_BM_CSTR_C-MODLID .
    IF SY-SUBRC EQ 0.
ZVI_BM_CSTR_C-MODTXT =
ZTB_BM_CSTR_M-MODTXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZVI_BM_CSTR_C.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVI_BM_CSTR_C .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVI_BM_CSTR_C.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVI_BM_CSTR_C-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTB_BM_CSTR_C WHERE
  MODLID = ZVI_BM_CSTR_C-MODLID AND
  CSFUNC = ZVI_BM_CSTR_C-CSFUNC .
    IF SY-SUBRC = 0.
    DELETE ZTB_BM_CSTR_C .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTB_BM_CSTR_C WHERE
  MODLID = ZVI_BM_CSTR_C-MODLID AND
  CSFUNC = ZVI_BM_CSTR_C-CSFUNC .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTB_BM_CSTR_C.
    ENDIF.
ZTB_BM_CSTR_C-MANDT =
ZVI_BM_CSTR_C-MANDT .
ZTB_BM_CSTR_C-MODLID =
ZVI_BM_CSTR_C-MODLID .
ZTB_BM_CSTR_C-CSFUNC =
ZVI_BM_CSTR_C-CSFUNC .
ZTB_BM_CSTR_C-TCODE =
ZVI_BM_CSTR_C-TCODE .
ZTB_BM_CSTR_C-VIEWNAME =
ZVI_BM_CSTR_C-VIEWNAME .
ZTB_BM_CSTR_C-VCL_NAME =
ZVI_BM_CSTR_C-VCL_NAME .
ZTB_BM_CSTR_C-DESCR =
ZVI_BM_CSTR_C-DESCR .
    IF SY-SUBRC = 0.
    UPDATE ZTB_BM_CSTR_C ##WARN_OK.
    ELSE.
    INSERT ZTB_BM_CSTR_C .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVI_BM_CSTR_C-UPD_FLAG,
STATUS_ZVI_BM_CSTR_C-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVI_BM_CSTR_C.
  SELECT SINGLE * FROM ZTB_BM_CSTR_C WHERE
MODLID = ZVI_BM_CSTR_C-MODLID AND
CSFUNC = ZVI_BM_CSTR_C-CSFUNC .
ZVI_BM_CSTR_C-MANDT =
ZTB_BM_CSTR_C-MANDT .
ZVI_BM_CSTR_C-MODLID =
ZTB_BM_CSTR_C-MODLID .
ZVI_BM_CSTR_C-CSFUNC =
ZTB_BM_CSTR_C-CSFUNC .
ZVI_BM_CSTR_C-TCODE =
ZTB_BM_CSTR_C-TCODE .
ZVI_BM_CSTR_C-VIEWNAME =
ZTB_BM_CSTR_C-VIEWNAME .
ZVI_BM_CSTR_C-VCL_NAME =
ZTB_BM_CSTR_C-VCL_NAME .
ZVI_BM_CSTR_C-DESCR =
ZTB_BM_CSTR_C-DESCR .
    SELECT SINGLE * FROM ZTB_BM_CSTR_M WHERE
MODLID = ZTB_BM_CSTR_C-MODLID .
    IF SY-SUBRC EQ 0.
ZVI_BM_CSTR_C-MODTXT =
ZTB_BM_CSTR_M-MODTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVI_BM_CSTR_C-MODTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVI_BM_CSTR_C USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVI_BM_CSTR_C-MODLID TO
ZTB_BM_CSTR_C-MODLID .
MOVE ZVI_BM_CSTR_C-CSFUNC TO
ZTB_BM_CSTR_C-CSFUNC .
MOVE ZVI_BM_CSTR_C-MANDT TO
ZTB_BM_CSTR_C-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTB_BM_CSTR_C'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTB_BM_CSTR_C TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTB_BM_CSTR_C'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVI_BM_CSTR_C USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZTB_BM_CSTR_C-MANDT =
ZVI_BM_CSTR_C-MANDT .
ZTB_BM_CSTR_C-MODLID =
ZVI_BM_CSTR_C-MODLID .
ZTB_BM_CSTR_C-CSFUNC =
ZVI_BM_CSTR_C-CSFUNC .
ZTB_BM_CSTR_C-TCODE =
ZVI_BM_CSTR_C-TCODE .
ZTB_BM_CSTR_C-VIEWNAME =
ZVI_BM_CSTR_C-VIEWNAME .
ZTB_BM_CSTR_C-VCL_NAME =
ZVI_BM_CSTR_C-VCL_NAME .
ZTB_BM_CSTR_C-DESCR =
ZVI_BM_CSTR_C-DESCR .
    SELECT SINGLE * FROM ZTB_BM_CSTR_M WHERE
MODLID = ZTB_BM_CSTR_C-MODLID .
    IF SY-SUBRC EQ 0.
ZVI_BM_CSTR_C-MODTXT =
ZTB_BM_CSTR_M-MODTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVI_BM_CSTR_C-MODTXT .
    ENDIF.
ENDFORM.
*...processing: ZVI_BM_CSTR_DEV.................................*
FORM GET_DATA_ZVI_BM_CSTR_DEV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTB_BM_CSTR_C WHERE
(VIM_WHERETAB) .
    CLEAR ZVI_BM_CSTR_DEV .
ZVI_BM_CSTR_DEV-MANDT =
ZTB_BM_CSTR_C-MANDT .
ZVI_BM_CSTR_DEV-MODLID =
ZTB_BM_CSTR_C-MODLID .
ZVI_BM_CSTR_DEV-CSFUNC =
ZTB_BM_CSTR_C-CSFUNC .
ZVI_BM_CSTR_DEV-TCODE =
ZTB_BM_CSTR_C-TCODE .
ZVI_BM_CSTR_DEV-VIEWNAME =
ZTB_BM_CSTR_C-VIEWNAME .
ZVI_BM_CSTR_DEV-VCL_NAME =
ZTB_BM_CSTR_C-VCL_NAME .
ZVI_BM_CSTR_DEV-DESCR =
ZTB_BM_CSTR_C-DESCR .
ZVI_BM_CSTR_DEV-STTURE =
ZTB_BM_CSTR_C-STTURE .
ZVI_BM_CSTR_DEV-FUNCMD =
ZTB_BM_CSTR_C-FUNCMD .
    SELECT SINGLE * FROM ZTB_BM_CSTR_M WHERE
MODLID = ZTB_BM_CSTR_C-MODLID .
    IF SY-SUBRC EQ 0.
ZVI_BM_CSTR_DEV-MODTXT =
ZTB_BM_CSTR_M-MODTXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZVI_BM_CSTR_DEV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVI_BM_CSTR_DEV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVI_BM_CSTR_DEV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVI_BM_CSTR_DEV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTB_BM_CSTR_C WHERE
  MODLID = ZVI_BM_CSTR_DEV-MODLID AND
  CSFUNC = ZVI_BM_CSTR_DEV-CSFUNC .
    IF SY-SUBRC = 0.
    DELETE ZTB_BM_CSTR_C .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTB_BM_CSTR_C WHERE
  MODLID = ZVI_BM_CSTR_DEV-MODLID AND
  CSFUNC = ZVI_BM_CSTR_DEV-CSFUNC .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTB_BM_CSTR_C.
    ENDIF.
ZTB_BM_CSTR_C-MANDT =
ZVI_BM_CSTR_DEV-MANDT .
ZTB_BM_CSTR_C-MODLID =
ZVI_BM_CSTR_DEV-MODLID .
ZTB_BM_CSTR_C-CSFUNC =
ZVI_BM_CSTR_DEV-CSFUNC .
ZTB_BM_CSTR_C-TCODE =
ZVI_BM_CSTR_DEV-TCODE .
ZTB_BM_CSTR_C-VIEWNAME =
ZVI_BM_CSTR_DEV-VIEWNAME .
ZTB_BM_CSTR_C-VCL_NAME =
ZVI_BM_CSTR_DEV-VCL_NAME .
ZTB_BM_CSTR_C-DESCR =
ZVI_BM_CSTR_DEV-DESCR .
ZTB_BM_CSTR_C-STTURE =
ZVI_BM_CSTR_DEV-STTURE .
ZTB_BM_CSTR_C-FUNCMD =
ZVI_BM_CSTR_DEV-FUNCMD .
    IF SY-SUBRC = 0.
    UPDATE ZTB_BM_CSTR_C ##WARN_OK.
    ELSE.
    INSERT ZTB_BM_CSTR_C .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVI_BM_CSTR_DEV-UPD_FLAG,
STATUS_ZVI_BM_CSTR_DEV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVI_BM_CSTR_DEV.
  SELECT SINGLE * FROM ZTB_BM_CSTR_C WHERE
MODLID = ZVI_BM_CSTR_DEV-MODLID AND
CSFUNC = ZVI_BM_CSTR_DEV-CSFUNC .
ZVI_BM_CSTR_DEV-MANDT =
ZTB_BM_CSTR_C-MANDT .
ZVI_BM_CSTR_DEV-MODLID =
ZTB_BM_CSTR_C-MODLID .
ZVI_BM_CSTR_DEV-CSFUNC =
ZTB_BM_CSTR_C-CSFUNC .
ZVI_BM_CSTR_DEV-TCODE =
ZTB_BM_CSTR_C-TCODE .
ZVI_BM_CSTR_DEV-VIEWNAME =
ZTB_BM_CSTR_C-VIEWNAME .
ZVI_BM_CSTR_DEV-VCL_NAME =
ZTB_BM_CSTR_C-VCL_NAME .
ZVI_BM_CSTR_DEV-DESCR =
ZTB_BM_CSTR_C-DESCR .
ZVI_BM_CSTR_DEV-STTURE =
ZTB_BM_CSTR_C-STTURE .
ZVI_BM_CSTR_DEV-FUNCMD =
ZTB_BM_CSTR_C-FUNCMD .
    SELECT SINGLE * FROM ZTB_BM_CSTR_M WHERE
MODLID = ZTB_BM_CSTR_C-MODLID .
    IF SY-SUBRC EQ 0.
ZVI_BM_CSTR_DEV-MODTXT =
ZTB_BM_CSTR_M-MODTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVI_BM_CSTR_DEV-MODTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVI_BM_CSTR_DEV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVI_BM_CSTR_DEV-MODLID TO
ZTB_BM_CSTR_C-MODLID .
MOVE ZVI_BM_CSTR_DEV-CSFUNC TO
ZTB_BM_CSTR_C-CSFUNC .
MOVE ZVI_BM_CSTR_DEV-MANDT TO
ZTB_BM_CSTR_C-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTB_BM_CSTR_C'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTB_BM_CSTR_C TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTB_BM_CSTR_C'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVI_BM_CSTR_DEV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZTB_BM_CSTR_C-MANDT =
ZVI_BM_CSTR_DEV-MANDT .
ZTB_BM_CSTR_C-MODLID =
ZVI_BM_CSTR_DEV-MODLID .
ZTB_BM_CSTR_C-CSFUNC =
ZVI_BM_CSTR_DEV-CSFUNC .
ZTB_BM_CSTR_C-TCODE =
ZVI_BM_CSTR_DEV-TCODE .
ZTB_BM_CSTR_C-VIEWNAME =
ZVI_BM_CSTR_DEV-VIEWNAME .
ZTB_BM_CSTR_C-VCL_NAME =
ZVI_BM_CSTR_DEV-VCL_NAME .
ZTB_BM_CSTR_C-DESCR =
ZVI_BM_CSTR_DEV-DESCR .
ZTB_BM_CSTR_C-STTURE =
ZVI_BM_CSTR_DEV-STTURE .
ZTB_BM_CSTR_C-FUNCMD =
ZVI_BM_CSTR_DEV-FUNCMD .
    SELECT SINGLE * FROM ZTB_BM_CSTR_M WHERE
MODLID = ZTB_BM_CSTR_C-MODLID .
    IF SY-SUBRC EQ 0.
ZVI_BM_CSTR_DEV-MODTXT =
ZTB_BM_CSTR_M-MODTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVI_BM_CSTR_DEV-MODTXT .
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
