FUNCTION ZFM_BM_CS_SALES_ORG_SDD156.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD156
*"----------------------------------------------------------------------
DATA:
         LSS_TVLK TYPE TVLK.
  GS_DATASD156 = I_DATA.
  SELECT SINGLE *
    FROM TVLK
    INTO CORRESPONDING FIELDS OF GT_SD156
    WHERE LFART = GS_DATASD156-LFART.
  IF  SY-SUBRC IS INITIAL.
    GS_SD156-LFART = GS_DATASD156-LFART.
    GS_SD156-CMGRL = GS_DATASD156-CMGRL.
    GS_SD156-CMGRW = GS_DATASD156-CMGRW.
    MOVE-CORRESPONDING GS_SD156 TO LSS_TVLK.
    UPDATE TVLK FROM LSS_TVLK.
  ELSE.
  GS_SD156-LFART = GS_DATASD156-LFART.
    GS_SD156-CMGRL = GS_DATASD156-CMGRL.
    GS_SD156-CMGRW = GS_DATASD156-CMGRW.
    MOVE-CORRESPONDING GS_SD156 TO LSS_TVLK.
    INSERT TVLK FROM LSS_TVLK.
  ENDIF.
ENDFUNCTION.
