FUNCTION ZFM_BM_CS_04_OKKP.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_CS_04_OKKP
*"----------------------------------------------------------------------
  DATA: LSS_TKA00       TYPE TKA00.

  GS_DATA04_OKKP = I_DATA.
  SELECT SINGLE
    *
      FROM TKA00
       INTO CORRESPONDING FIELDS OF  GT_04_OKKP
      WHERE KOKRS = GS_DATA04_OKKP-KOKRS
    AND GJAHR = GS_DATA04_OKKP-GJAHR.
  IF SY-SUBRC IS INITIAL.
    GS_04_OKKP-KOKRS = GS_DATA04_OKKP-KOKRS.
    GS_04_OKKP-GJAHR = GS_DATA04_OKKP-GJAHR.
    GS_04_OKKP-KOSTS = GS_DATA04_OKKP-KOSTS.
    GS_04_OKKP-AUFTR = GS_DATA04_OKKP-AUFTR.
    GS_04_OKKP-ERGBR = GS_DATA04_OKKP-ERGBR.
    GS_04_OKKP-PRJKT = GS_DATA04_OKKP-PRJKT.
    GS_04_OKKP-RABWG = GS_DATA04_OKKP-RABWG.
    GS_04_OKKP-OAUFT = GS_DATA04_OKKP-OAUFT.
    GS_04_OKKP-MATST = GS_DATA04_OKKP-MATST.
    GS_04_OKKP-ALLEW = GS_DATA04_OKKP-ALLEW.
    GS_04_OKKP-RKBUK = GS_DATA04_OKKP-RKBUK.
    GS_04_OKKP-PCRCH = GS_DATA04_OKKP-PCRCH.
    GS_04_OKKP-RVAUF = GS_DATA04_OKKP-RVAUF.
    GS_04_OKKP-OBLVB = GS_DATA04_OKKP-OBLVB.
    GS_04_OKKP-COABC = GS_DATA04_OKKP-COABC.
    GS_04_OKKP-KKALK = GS_DATA04_OKKP-KKALK.
    GS_04_OKKP-HHPLN = GS_DATA04_OKKP-HHPLN.
    GS_04_OKKP-RMBST = GS_DATA04_OKKP-RMBST.
    GS_04_OKKP-RMKAL = GS_DATA04_OKKP-RMKAL.
    GS_04_OKKP-ANLAA = GS_DATA04_OKKP-ANLAA.
    GS_04_OKKP-RFKUN = GS_DATA04_OKKP-RFKUN.
    GS_04_OKKP-RFDIS = GS_DATA04_OKKP-RFDIS.
    GS_04_OKKP-GLSYS = GS_DATA04_OKKP-GLSYS.
    GS_04_OKKP-RPPER = GS_DATA04_OKKP-RPPER.
    GS_04_OKKP-RVFAK = GS_DATA04_OKKP-RVFAK.
    GS_04_OKKP-RFZAL = GS_DATA04_OKKP-RFZAL.
    GS_04_OKKP-RFANZ = GS_DATA04_OKKP-RFANZ.
    GS_04_OKKP-KAEIN = GS_DATA04_OKKP-KAEIN.
    GS_04_OKKP-ACTPA = GS_DATA04_OKKP-ACTPA.
    GS_04_OKKP-REACTIVE = GS_DATA04_OKKP-REACTIVE.
    GS_04_OKKP-ADD_HIER1 = GS_DATA04_OKKP-ADD_HIER1.
    GS_04_OKKP-ADD_HIER2 = GS_DATA04_OKKP-ADD_HIER2.
    GS_04_OKKP-KE_ADD_HIER1 = GS_DATA04_OKKP-KE_ADD_HIER1.
    GS_04_OKKP-KE_ADD_HIER2 = GS_DATA04_OKKP-KE_ADD_HIER2.
    GS_04_OKKP-PCTRP = GS_DATA04_OKKP-PCTRP.
    GS_04_OKKP-PSL_ACTIVE = GS_DATA04_OKKP-PSL_ACTIVE.

    MOVE-CORRESPONDING GS_04_OKKP TO LSS_TKA00.
    UPDATE TKA00 FROM LSS_TKA00.
  ELSE.
    GS_04_OKKP-KOKRS = GS_DATA04_OKKP-KOKRS.
    GS_04_OKKP-GJAHR = GS_DATA04_OKKP-GJAHR.
    GS_04_OKKP-KOSTS = GS_DATA04_OKKP-KOSTS.
    GS_04_OKKP-AUFTR = GS_DATA04_OKKP-AUFTR.
    GS_04_OKKP-ERGBR = GS_DATA04_OKKP-ERGBR.
    GS_04_OKKP-PRJKT = GS_DATA04_OKKP-PRJKT.
    GS_04_OKKP-RABWG = GS_DATA04_OKKP-RABWG.
    GS_04_OKKP-OAUFT = GS_DATA04_OKKP-OAUFT.
    GS_04_OKKP-MATST = GS_DATA04_OKKP-MATST.
    GS_04_OKKP-ALLEW = GS_DATA04_OKKP-ALLEW.
    GS_04_OKKP-RKBUK = GS_DATA04_OKKP-RKBUK.
    GS_04_OKKP-PCRCH = GS_DATA04_OKKP-PCRCH.
    GS_04_OKKP-RVAUF = GS_DATA04_OKKP-RVAUF.
    GS_04_OKKP-OBLVB = GS_DATA04_OKKP-OBLVB.
    GS_04_OKKP-COABC = GS_DATA04_OKKP-COABC.
    GS_04_OKKP-KKALK = GS_DATA04_OKKP-KKALK.
    GS_04_OKKP-HHPLN = GS_DATA04_OKKP-HHPLN.
    GS_04_OKKP-RMBST = GS_DATA04_OKKP-RMBST.
    GS_04_OKKP-RMKAL = GS_DATA04_OKKP-RMKAL.
    GS_04_OKKP-ANLAA = GS_DATA04_OKKP-ANLAA.
    GS_04_OKKP-RFKUN = GS_DATA04_OKKP-RFKUN.
    GS_04_OKKP-RFDIS = GS_DATA04_OKKP-RFDIS.
    GS_04_OKKP-GLSYS = GS_DATA04_OKKP-GLSYS.
    GS_04_OKKP-RPPER = GS_DATA04_OKKP-RPPER.
    GS_04_OKKP-RVFAK = GS_DATA04_OKKP-RVFAK.
    GS_04_OKKP-RFZAL = GS_DATA04_OKKP-RFZAL.
    GS_04_OKKP-RFANZ = GS_DATA04_OKKP-RFANZ.
    GS_04_OKKP-KAEIN = GS_DATA04_OKKP-KAEIN.
    GS_04_OKKP-ACTPA = GS_DATA04_OKKP-ACTPA.
    GS_04_OKKP-REACTIVE = GS_DATA04_OKKP-REACTIVE.
    GS_04_OKKP-ADD_HIER1 = GS_DATA04_OKKP-ADD_HIER1.
    GS_04_OKKP-ADD_HIER2 = GS_DATA04_OKKP-ADD_HIER2.
    GS_04_OKKP-KE_ADD_HIER1 = GS_DATA04_OKKP-KE_ADD_HIER1.
    GS_04_OKKP-KE_ADD_HIER2 = GS_DATA04_OKKP-KE_ADD_HIER2.
    GS_04_OKKP-PCTRP = GS_DATA04_OKKP-PCTRP.
    GS_04_OKKP-PSL_ACTIVE = GS_DATA04_OKKP-PSL_ACTIVE.

    MOVE-CORRESPONDING GS_04_OKKP TO LSS_TKA00.
    INSERT  TKA00 FROM LSS_TKA00.
  ENDIF.
ENDFUNCTION.
