FUNCTION ZFM_BM_CS_SALES_ORG_SD107.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD107
*"----------------------------------------------------------------------
 DATA: LSS_TVKOS     TYPE TVKOS.

  GS_DATASD107 = I_DATA.
  SELECT SINGLE
    *
      FROM TVKOS
       INTO CORRESPONDING FIELDS OF  GT_SD107
      WHERE VKORG = GS_DATASD107-VKORG .
  IF SY-SUBRC IS INITIAL.
    GS_SD107-VKORG = GS_DATASD107-VKORG.
    GS_SD107-SPART = GS_DATASD107-SPART.
    GS_SD107-SPAAU = GS_DATASD107-SPAAU.

    MOVE-CORRESPONDING GS_SD107 TO LSS_TVKOS.
    UPDATE  TVKOS FROM LSS_TVKOS.

  ELSE.
    GS_SD107-VKORG = GS_DATASD107-VKORG.
    GS_SD107-SPART = GS_DATASD107-SPART.
    GS_SD107-SPAAU = GS_DATASD107-SPAAU.

    MOVE-CORRESPONDING GS_SD107 TO LSS_TVKOS.
    INSERT  TVKOS FROM LSS_TVKOS.
  ENDIF.
ENDFUNCTION..
