FUNCTION ZFM_BM_CS_SALES_ORG_SD31.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD31
*"----------------------------------------------------------------------

DATA: LSS_TVPG           TYPE TVPG,
        LS_TVPAG TYPE TVPAG.

  GS_DATASD31 = I_DATA.
  SELECT SINGLE
    TVPG~PARGR,
    TVPAG~VTEXT
      FROM TVPG
    INNER JOIN TVPAG
    ON TVPAG~PARGR = TVPG~PARGR
       INTO CORRESPONDING FIELDS OF  @GT_SD31
      WHERE TVPG~PARGR = @GS_DATASD31-PARGR.
  IF SY-SUBRC IS INITIAL.

    GS_SD31-PARGR = GS_DATASD31-PARGR.
    GS_SD31-VTEXT = GS_DATASD31-VTEXT.
    GS_SD31-PAOBJ = 'B'.
    GS_SD31-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD31 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD31 TO LS_TVPAG.

    UPDATE  TVPG FROM LSS_TVPG.
    UPDATE  TVPAG FROM LS_TVPAG.
  ELSE.
     GS_SD31-PARGR = GS_DATASD31-PARGR.
    GS_SD31-VTEXT = GS_DATASD31-VTEXT.
    GS_SD31-PAOBJ = 'A'.
    GS_SD31-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD31 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD31 TO LS_TVPAG.

    INSERT  TVPG FROM LSS_TVPG.
    INSERT  TVPAG FROM LS_TVPAG.
  ENDIF.
ENDFUNCTION.
