FUNCTION ZFM_BM_CS_SALES_ORG_SD49.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD49
*"----------------------------------------------------------------------
DATA: LSS_TVPG           TYPE TVPG,
        LS_TVPAG TYPE TVPAG.

  GS_DATASD49 = I_DATA.
  SELECT SINGLE
    TVPG~PARGR,
    TVPAG~VTEXT
      FROM TVPG
    INNER JOIN TVPAG
    ON TVPAG~PARGR = TVPG~PARGR
       INTO CORRESPONDING FIELDS OF  @GT_SD49
      WHERE TVPG~PARGR = @GS_DATASD49-PARGR.
  IF SY-SUBRC IS INITIAL.

    GS_SD49-PARGR = GS_DATASD49-PARGR.
    GS_SD49-VTEXT = GS_DATASD49-VTEXT.
    GS_SD49-PAOBJ = 'E'.
    GS_SD49-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD49 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD49 TO LS_TVPAG.

    UPDATE  TVPG FROM LSS_TVPG.
    UPDATE  TVPAG FROM LS_TVPAG.
  ELSE.

    GS_SD49-PARGR = GS_DATASD49-PARGR.
    GS_SD49-VTEXT = GS_DATASD49-VTEXT.
    GS_SD49-PAOBJ = 'E'.
    GS_SD49-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD49 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD49 TO LS_TVPAG.

    INSERT  TVPG FROM LSS_TVPG.
    INSERT  TVPAG FROM LS_TVPAG.
  ENDIF.
ENDFUNCTION.
