FUNCTION ZFM_BM_CS_SALES_ORG_SD13.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD13
*"----------------------------------------------------------------------
DATA: LSS_TVSWZ        TYPE TVSWZ.

  GS_DATASD13 = I_DATA.
  SELECT SINGLE
    *
      FROM TVSWZ
       INTO CORRESPONDING FIELDS OF  GT_SD13
      WHERE WERKS = GS_DATASD13-WERKS
    AND VSTEL = GS_DATASD13-VSTEL .
  IF SY-SUBRC IS INITIAL.
    GS_SD13-WERKS = GS_DATASD13-WERKS.
    GS_SD13-VSTEL = GS_DATASD13-VSTEL.
    MOVE-CORRESPONDING GS_SD13 TO LSS_TVSWZ.
    UPDATE  TVSWZ FROM LSS_TVSWZ.

  ELSE.
    GS_SD13-WERKS = GS_DATASD13-WERKS.
    GS_SD13-VSTEL = GS_DATASD13-VSTEL.
    MOVE-CORRESPONDING GS_SD13 TO LSS_TVSWZ.
    INSERT  TVSWZ FROM LSS_TVSWZ.

  ENDIF.
ENDFUNCTION.
