FUNCTION-POOL ZFG_BM_COMPANYCODE.           "MESSAGE-ID ..

* INCLUDE LZFG_BM_COMPANYCODED...            " Local class definition
TABLES: T001 .
TABLES:T001A.
DATA:
  GS_DATA   TYPE  ZST_BM_V_T001_ADDRESS,
  GT_RETURN TYPE  TABLE OF BAPIRET2,
  G_MODE    TYPE C.
DATA: ADTEL_WA TYPE SZADR_ADTEL_LINE.

DATA: BEGIN OF ADTEL OCCURS 0.
        INCLUDE STRUCTURE ADTEL.
DATA: END OF ADTEL.
DATA: BEGIN OF ADFAX OCCURS 0.
        INCLUDE STRUCTURE ADFAX.
DATA: END OF ADFAX.
DATA: BEGIN OF ADSMTP OCCURS 0.
        INCLUDE STRUCTURE ADSMTP.
DATA: END OF ADSMTP.
DATA: BEGIN OF E_TABLE OCCURS 0.
        INCLUDE STRUCTURE ADDR_ERROR.
DATA: END OF E_TABLE.
TYPES:

  BEGIN OF SZADR_ADTEL_LINE,
    DATE_FROM LIKE ADRC-DATE_FROM,
    ADTEL     LIKE ADTEL,
  END OF SZADR_ADTEL_LINE.
DATA:    BEGIN OF IT882 OCCURS 15.
           INCLUDE STRUCTURE T882.
DATA:    END OF IT882.
DATA:    BEGIN OF IRFCTP OCCURS 10.
           INCLUDE STRUCTURE RFCTP.
DATA:    END OF IRFCTP.
DATA: BEGIN OF V_T001_TOTAL OCCURS 0100.
        INCLUDE STRUCTURE V_T001.
        INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF V_T001_TOTAL.
DATA: BEGIN OF BUKRSTAB OCCURS 5,
        BUKRS LIKE T001-BUKRS,
      END   OF BUKRSTAB.
DATA: RC     LIKE SY-SUBRC,      " Return-Code
      RC_OBJ LIKE SY-SUBRC,      " Return-Code
      TABLE  LIKE T800A-TAB.     " Tabellenname
