FUNCTION ZFM_BM_CS_SALES_ORG_SD44.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD44
*"----------------------------------------------------------------------
DATA: LSS_TVPG           TYPE TVPG,
        LS_TVPAG TYPE TVPAG.

  GS_DATASD44 = I_DATA.
  SELECT SINGLE
    TVPG~PARGR,
    TVPAG~VTEXT
      FROM TVPG
    INNER JOIN TVPAG
    ON TVPAG~PARGR = TVPG~PARGR
       INTO CORRESPONDING FIELDS OF  @GT_SD44
      WHERE TVPG~PARGR = @GS_DATASD44-PARGR.
  IF SY-SUBRC IS INITIAL.

    GS_SD44-PARGR = GS_DATASD44-PARGR.
    GS_SD44-VTEXT = GS_DATASD44-VTEXT.
    GS_SD44-PAOBJ = 'N'.
    GS_SD44-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD44 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD44 TO LS_TVPAG.

    UPDATE  TVPG FROM LSS_TVPG.
    UPDATE  TVPAG FROM LS_TVPAG.
  ELSE.
      GS_SD44-PARGR = GS_DATASD44-PARGR.
    GS_SD44-VTEXT = GS_DATASD44-VTEXT.
    GS_SD44-PAOBJ = 'N'.
    GS_SD44-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD44 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD44 TO LS_TVPAG.

    INSERT  TVPG FROM LSS_TVPG.
    INSERT  TVPAG FROM LS_TVPAG.
  ENDIF.
ENDFUNCTION.
