FUNCTION ZFM_BM_CS_SALES_ORG_SD09.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD09
*"----------------------------------------------------------------------
  DATA: LSS_TVKOV           TYPE TVKOV,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  GS_DATASD09 = I_DATA.
  SELECT SINGLE
    TVKOV~VKORG,
    TVKOV~VTWEG,
    TASSIGN_SD_VKORG~STATUS_ASSIGN_SD,
    TVKOV~VTWKO,
    TVKOV~VTWAU,
    TVKOV~VTWKU,
    TVKOV~HIDE
      FROM TVKOV
    INNER JOIN TASSIGN_SD_VKORG
    ON TASSIGN_SD_VKORG~VKORG = TVKOV~VKORG
       INTO CORRESPONDING FIELDS OF   @GT_TVKOV
      WHERE TVKOV~VKORG = @GS_DATASD09-VKORG
    AND TVKOV~VTWEG  =  @GS_DATASD09-VTWEG.
  IF SY-SUBRC IS INITIAL.
    PERFORM CHECKUPDATE.
    GS_TVKOV-VKORG = GS_DATASD09-VKORG.
    GS_TVKOV-VTWEG = GS_DATASD09-VTWEG.
    GS_TVKOV-VTWKO = GS_DATASD09-VTWKO.
    GS_TVKOV-VTWAU = GS_DATASD09-VTWAU.
    GS_TVKOV-VTWKU = GS_DATASD09-VTWKU.
    GS_TVKOV-HIDE = GS_DATASD09-HIDE.

    MOVE-CORRESPONDING GS_TVKOV TO LSS_TVKOV.
    MOVE-CORRESPONDING GS_TVKOV TO LS_TASSIGN_SD_VKORG.

    UPDATE  TVKOV FROM LSS_TVKOV.
    UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ELSE.
    GS_TVKOV-VKORG = GS_DATASD09-VKORG.
    GS_TVKOV-VTWEG = GS_DATASD09-VTWEG.
    GS_TVKOV-VTWKO = GS_DATASD09-VTWKO.
    GS_TVKOV-VTWAU = GS_DATASD09-VTWAU.
    GS_TVKOV-VTWKU = GS_DATASD09-VTWKU.
    GS_TVKOV-HIDE  = GS_DATASD09-HIDE.

    MOVE-CORRESPONDING GS_TVKOV TO LSS_TVKOV.
    MOVE-CORRESPONDING GS_TVKOV TO LS_TASSIGN_SD_VKORG.
    INSERT  TVKOV FROM LSS_TVKOV.
    INSERT  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ENDIF.
ENDFUNCTION.
FORM CHECKUPDATE.
  DATA:
    LS_TVKOV TYPE TVKOV,
    I_DATA   TYPE  ZST_BM_SALES_SD09.
  DATA: LSS_TVKOV           TYPE TVKOV,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  I_DATA = GS_DATASD09.
  SELECT SINGLE
    VKORG
      FROM TVKOV
      INTO CORRESPONDING FIELDS OF  LS_TVKOV
      WHERE VKORG = GS_DATASD09-VKORG
    AND VTWEG  =  GS_DATASD09-VTWEG.

  IF SY-SUBRC IS INITIAL .
    IF  GS_DATASD09-VTWEG  IS INITIAL
      AND GS_DATASD09-STATUS_ASSIGN_SD IS INITIAL
      AND GS_DATASD09-VTWKO IS INITIAL
      AND GS_DATASD09-VTWAU IS INITIAL
      AND GS_DATASD09-VTWKU IS INITIAL
      AND GS_DATASD09-HIDE IS INITIAL.
    ELSE.
      GS_TVKOV-VKORG = GS_DATASD09-VKORG.
      GS_TVKOV-VTWEG = GS_DATASD09-VTWEG.
      GS_TVKOV-VTWKO = GS_DATASD09-VTWKO.
      GS_TVKOV-VTWAU = GS_DATASD09-VTWAU.
      GS_TVKOV-VTWKU = GS_DATASD09-VTWKU.
      GS_TVKOV-HIDE = GS_DATASD09-HIDE.
      MOVE-CORRESPONDING GS_TVKOV TO LSS_TVKOV.
      MOVE-CORRESPONDING GS_TVKOV TO LS_TASSIGN_SD_VKORG.
      UPDATE  TVKOV FROM LSS_TVKOV.
      UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
    ENDIF.
  ENDIF.
ENDFORM.
