FUNCTION ZFM_BM_CS_SALES_ORG_SDD192.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD192
*"----------------------------------------------------------------------
DATA:
         LSS_TVTK TYPE TVTK.
  GS_DATASD192 = I_DATA.
  SELECT SINGLE *
    FROM TVTK
    INTO CORRESPONDING FIELDS OF GT_SD192
    WHERE SHTYP = GS_DATASD192-SHTYP.
  IF  SY-SUBRC IS INITIAL.
    GS_SD192-SHTYP = GS_DATASD192-SHTYP.
    GS_SD192-FKART = GS_DATASD192-FKART.
    MOVE-CORRESPONDING GS_SD192 TO LSS_TVTK.
    UPDATE TVTK FROM LSS_TVTK.
  ELSE.
  GS_SD192-SHTYP = GS_DATASD192-SHTYP.
    GS_SD192-FKART = GS_DATASD192-FKART.
    MOVE-CORRESPONDING GS_SD192 TO LSS_TVTK.
    INSERT TVTK FROM LSS_TVTK.
  ENDIF.
ENDFUNCTION.
