FUNCTION ZFM_BM_CS_SALES_ORG_SDD169.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD169
*"----------------------------------------------------------------------
DATA:
         LSS_TVTA TYPE TVTA.
  GS_DATASD169 = I_DATA.
  SELECT SINGLE *
    FROM TVTA
    INTO CORRESPONDING FIELDS OF GT_SD169
    WHERE VKORG = GS_DATASD169-VKORG
    AND VTWEG = GS_DATASD169-VTWEG
    AND SPART = GS_DATASD169-SPART.
  IF  SY-SUBRC IS INITIAL.
    GS_SD169-VKORG = GS_DATASD169-VKORG.
    GS_SD169-VTWEG = GS_DATASD169-VTWEG.
    GS_SD169-SPART = GS_DATASD169-SPART.
    GS_SD169-KKBER = GS_DATASD169-KKBER.
    MOVE-CORRESPONDING GS_SD169 TO LSS_TVTA.
    UPDATE TVTA FROM LSS_TVTA.
  ELSE.
   GS_SD169-VKORG = GS_DATASD169-VKORG.
    GS_SD169-VTWEG = GS_DATASD169-VTWEG.
    GS_SD169-SPART = GS_DATASD169-SPART.
    GS_SD169-KKBER = GS_DATASD169-KKBER.
    MOVE-CORRESPONDING GS_SD169 TO LSS_TVTA.
    INSERT TVTA FROM LSS_TVTA.
  ENDIF.
ENDFUNCTION.
