FUNCTION ZFM_BM_CS_SALES_ORG_SDD214.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD214
*"----------------------------------------------------------------------
DATA:
         LSS_TVAK TYPE TVAK.
  GS_DATASD214 = I_DATA.
  SELECT SINGLE *
    FROM TVAK
    INTO CORRESPONDING FIELDS OF GT_SD214
    WHERE AUART = GS_DATASD214-AUART.
  IF  SY-SUBRC IS INITIAL.
    GS_SD214-AUART = GS_DATASD214-AUART.
    GS_SD214-STGAK = GS_DATASD214-STGAK.
    MOVE-CORRESPONDING GS_SD214 TO LSS_TVAK.
    UPDATE TVAK FROM LSS_TVAK.
  ELSE.
     GS_SD214-AUART = GS_DATASD214-AUART.
    GS_SD214-STGAK = GS_DATASD214-STGAK.
    MOVE-CORRESPONDING GS_SD214 TO LSS_TVAK.
    INSERT TVAK FROM LSS_TVAK.
  ENDIF.
ENDFUNCTION.
