FUNCTION ZFM_BM_CS_SALES_ORG_SD26.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD26
*"----------------------------------------------------------------------
DATA: LSS_TVPG           TYPE TVPG,
        LS_TVPAG TYPE TVPAG.

  GS_DATASD26 = I_DATA.
  SELECT SINGLE
    TVPG~PARGR,
    TVPAG~VTEXT
      FROM TVPG
    INNER JOIN TVPAG
    ON TVPAG~PARGR = TVPG~PARGR
       INTO CORRESPONDING FIELDS OF  @GT_SD26
      WHERE TVPG~PARGR = @GS_DATASD26-PARGR.
  IF SY-SUBRC IS INITIAL.
*    PERFORM CHECKSD26.
    GS_SD26-PARGR = GS_DATASD26-PARGR.
    GS_SD26-VTEXT = GS_DATASD26-VTEXT.
    GS_SD26-PAOBJ = 'A'.
    GS_SD26-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD26 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD26 TO LS_TVPAG.

    UPDATE  TVPG FROM LSS_TVPG.
    UPDATE  TVPAG FROM LS_TVPAG.
  ELSE.
     GS_SD26-PARGR = GS_DATASD26-PARGR.
    GS_SD26-VTEXT = GS_DATASD26-VTEXT.
    GS_SD26-PAOBJ = 'A'.
    GS_SD26-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD26 TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD26 TO LS_TVPAG.

    INSERT  TVPG FROM LSS_TVPG.
    INSERT  TVPAG FROM LS_TVPAG.
  ENDIF.
ENDFUNCTION.
*FORM CHECKSD26.
*  DATA:
*    LS_TVKO TYPE TVPG,
*    I_DATA  TYPE  ZST_BM_SALES_SD08.
*  DATA: LSS_TVKO            TYPE TVKO,
*        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.
*
*  I_DATA = GS_DATASD08.
*  SELECT SINGLE
*    VKORG
*      FROM TVKO
*      INTO CORRESPONDING FIELDS OF  LS_TVKO
*      WHERE VKORG = GS_DATASD08-VKORG.
*
*  IF SY-SUBRC IS INITIAL .
*    IF  GS_DATASD08-BUKRS IS INITIAL.
*
*    ELSE.
*      GS_SD08-VKORG = GS_DATASD08-VKORG.
*      GS_SD08-BUKRS = GS_DATASD08-BUKRS.
*      MOVE-CORRESPONDING GS_SD08 TO LSS_TVKO.
*      MOVE-CORRESPONDING GS_SD08 TO LS_TASSIGN_SD_VKORG.
*
*      UPDATE  TVKO FROM LSS_TVKO.
*      UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
*    ENDIF.
*  ENDIF.
*ENDFORM.
