FUNCTION ZFM_BM_CS_SALES_ORG_SD108.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD108
*"----------------------------------------------------------------------
DATA: LSS_TVAKZ    TYPE TVAKZ.

  GS_DATASD108 = I_DATA.
  SELECT SINGLE
    *
      FROM TVAKZ
       INTO CORRESPONDING FIELDS OF  GT_SD108
      WHERE VKORG = GS_DATASD108-VKORG .
  IF SY-SUBRC IS INITIAL.
    GS_SD108-VKORG = GS_DATASD108-VKORG.
    GS_SD108-VTWEG = GS_DATASD108-VTWEG.
    GS_SD108-SPART = GS_DATASD108-SPART.
    GS_SD108-AUART = GS_DATASD108-AUART.

    MOVE-CORRESPONDING GS_SD108 TO LSS_TVAKZ.
    UPDATE  TVAKZ FROM LSS_TVAKZ.

  ELSE.
    GS_SD108-VKORG = GS_DATASD108-VKORG.
    GS_SD108-VTWEG = GS_DATASD108-VTWEG.
    GS_SD108-SPART = GS_DATASD108-SPART.
    GS_SD108-AUART = GS_DATASD108-AUART.

    MOVE-CORRESPONDING GS_SD108 TO LSS_TVAKZ.
    INSERT  TVAKZ FROM LSS_TVAKZ.
  ENDIF.
ENDFUNCTION.
