FUNCTION ZFM_BM_CS_SALES_ORG_SD41 .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD42
*"----------------------------------------------------------------------
DATA: LSS_TVLK         TYPE TVLK.

  GS_DATASD42 = I_DATA.
  SELECT SINGLE
    *
      FROM TVLK
       INTO CORRESPONDING FIELDS OF  GT_SD42
      WHERE LFART = GS_DATASD42-LFART.
  IF SY-SUBRC IS INITIAL.
    GS_SD42-LFART = GS_DATASD42-LFART.
    GS_SD42-PARGR = GS_DATASD42-PARGR.
    MOVE-CORRESPONDING GS_SD42 TO LSS_TVLK.
    UPDATE  TVLK FROM LSS_TVLK.

  ELSE.
     GS_SD42-LFART = GS_DATASD42-LFART.
    GS_SD42-PARGR = GS_DATASD42-PARGR.
    MOVE-CORRESPONDING GS_SD42 TO LSS_TVLK.
    INSERT  TVLK FROM LSS_TVLK.
  ENDIF.
ENDFUNCTION.
