FUNCTION ZFM_BM_CS_SALES_ORG_SD11.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD11
*"----------------------------------------------------------------------
  DATA: LSS_TVTA            TYPE TVTA,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  GS_DATASD11 = I_DATA.
  SELECT SINGLE
     TVTA~VKORG,
     TVTA~VTWEG,
     TVTA~SPART,
     TASSIGN_SD_VKORG~STATUS_ASSIGN_SD,
     TVTA~SPAKU,
     TVTA~SPAKO,
     TVTA~SPAAU,
     TVTA~VTWKU,
     TVTA~VTWKO,
     TVTA~VKOAU,
     TVTA~VTWAU,
     TVTA~HIDE
     FROM TVTA
     INNER JOIN TASSIGN_SD_VKORG
     ON TASSIGN_SD_VKORG~VKORG = TVTA~VKORG
        INTO CORRESPONDING FIELDS OF  @GT_SD11
       WHERE TVTA~VKORG = @GS_DATASD11-VKORG
     AND TVTA~SPART = @GS_DATASD11-SPART
     AND TVTA~VTWEG = @GS_DATASD11-VTWEG.

  IF SY-SUBRC IS INITIAL.
    PERFORM CHECKSD11.
    GS_SD11-VKORG = GS_DATASD11-VKORG.
    GS_SD11-VTWEG = GS_DATASD11-VTWEG.
    GS_SD11-SPART = GS_DATASD11-SPART.
    GS_SD11-SPAKU = GS_DATASD11-SPAKU.
    GS_SD11-SPAKO = GS_DATASD11-SPAKO.
    GS_SD11-SPAAU = GS_DATASD11-SPAAU.
    GS_SD11-VTWKU = GS_DATASD11-VTWKU.
    GS_SD11-VTWKO = GS_DATASD11-VTWKO.
    GS_SD11-VKOAU = GS_DATASD11-VTWAU.
    GS_SD11-VTWAU = GS_DATASD11-SPAAU.
    GS_SD11-HIDE = GS_DATASD11-HIDE.
    MOVE-CORRESPONDING GS_SD11 TO LSS_TVTA.
    MOVE-CORRESPONDING GS_SD11 TO LS_TASSIGN_SD_VKORG.

    UPDATE  TVTA FROM LSS_TVTA.
    UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ELSE.
    GS_SD11-VKORG = GS_DATASD11-VKORG.
    GS_SD11-VTWEG = GS_DATASD11-VTWEG.
    GS_SD11-SPART = GS_DATASD11-SPART.
    GS_SD11-SPAKU = GS_DATASD11-SPAKU.
    GS_SD11-SPAKO = GS_DATASD11-SPAKO.
    GS_SD11-SPAAU = GS_DATASD11-SPAAU.
    GS_SD11-VTWKU = GS_DATASD11-VTWKU.
    GS_SD11-VTWKO = GS_DATASD11-VTWKO.
    GS_SD11-VKOAU = GS_DATASD11-VTWAU.
    GS_SD11-VTWAU = GS_DATASD11-SPAAU.
    GS_SD11-HIDE = GS_DATASD11-HIDE.
    MOVE-CORRESPONDING GS_SD11 TO LSS_TVTA.
    MOVE-CORRESPONDING GS_SD11 TO LS_TASSIGN_SD_VKORG.

    INSERT  TVTA FROM LSS_TVTA.
    INSERT  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ENDIF.
ENDFUNCTION.
FORM CHECKSD11.
  DATA:
    LS_TVTA TYPE TVTA,
    I_DATA  TYPE  ZST_BM_SALES_SD11.
  DATA: LSS_TVTA            TYPE TVTA,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  I_DATA = GS_DATASD11.
  SELECT SINGLE
    VKORG
      FROM TVTA
      INTO CORRESPONDING FIELDS OF  LS_TVTA
      WHERE VKORG = GS_DATASD11-VKORG
      AND TVTA~SPART = GS_DATASD11-SPART
     AND TVTA~VTWEG = GS_DATASD11-VTWEG.

  IF SY-SUBRC IS INITIAL .
    IF  GS_DATASD11-SPART  IS INITIAL
      AND GS_DATASD11-VTWEG  IS INITIAL
      AND GS_DATASD11-SPAKU  IS INITIAL
      AND GS_DATASD11-SPAKO  IS INITIAL
      AND GS_DATASD11-SPAAU  IS INITIAL
      AND GS_DATASD11-VTWKU  IS INITIAL
      AND GS_DATASD11-VTWKO  IS INITIAL
      AND GS_DATASD11-VKOAU  IS INITIAL
      AND GS_DATASD11-VTWAU  IS INITIAL
      AND GS_DATASD11-HIDE  IS INITIAL.
    ELSE.
      GS_SD11-VKORG = GS_DATASD11-VKORG.
      GS_SD11-VTWEG = GS_DATASD11-VTWEG.
      GS_SD11-SPART = GS_DATASD11-SPART.
      GS_SD11-SPAKU = GS_DATASD11-SPAKU.
      GS_SD11-SPAKO = GS_DATASD11-SPAKO.
      GS_SD11-SPAAU = GS_DATASD11-SPAAU.
      GS_SD11-VTWKU = GS_DATASD11-VTWKU.
      GS_SD11-VTWKO = GS_DATASD11-VTWKO.
      GS_SD11-VKOAU = GS_DATASD11-VTWAU.
      GS_SD11-VTWAU = GS_DATASD11-SPAAU.
      GS_SD11-HIDE = GS_DATASD11-HIDE.
      MOVE-CORRESPONDING GS_SD11 TO LSS_TVTA.
      MOVE-CORRESPONDING GS_SD11 TO LS_TASSIGN_SD_VKORG.

      UPDATE  TVTA FROM LSS_TVTA.
      UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
    ENDIF.
  ENDIF.
ENDFORM.
