FUNCTION ZFM_BM_CS_SALES_ORG_SD10.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD10
*"----------------------------------------------------------------------

  DATA: LSS_TVKOS           TYPE TVKOS,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  GS_DATASD10 = I_DATA.
  SELECT SINGLE
     TVKOS~VKORG,
     TVKOS~SPART,
     TASSIGN_SD_VKORG~STATUS_ASSIGN_SD,
     TVKOS~SPAKU,
     TVKOS~SPAKO,
     TVKOS~SPAAU,
     TVKOS~HIDE
     FROM TVKOS
     INNER JOIN TASSIGN_SD_VKORG
     ON TASSIGN_SD_VKORG~VKORG = TVKOS~VKORG
        INTO CORRESPONDING FIELDS OF  @GT_SD10
       WHERE TVKOS~VKORG = @GS_DATASD10-VKORG
     AND TVKOS~SPART = @GS_DATASD10-SPART.

  IF SY-SUBRC IS INITIAL.
    PERFORM CHECKSD10.
    GS_SD10-VKORG = GS_DATASD10-VKORG.
    GS_SD10-SPART = GS_DATASD10-SPART.
    GS_SD10-SPAKU = GS_DATASD10-SPAKU.
    GS_SD10-SPAKO = GS_DATASD10-SPAKO.
    GS_SD10-SPAAU = GS_DATASD10-SPAAU.
    GS_SD10-HIDE = GS_DATASD10-HIDE.
    MOVE-CORRESPONDING GS_SD10 TO LSS_TVKOS.
    MOVE-CORRESPONDING GS_SD10 TO LS_TASSIGN_SD_VKORG.

    UPDATE  TVKOS FROM LSS_TVKOS.
    UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ELSE.
    GS_SD10-VKORG = GS_DATASD10-VKORG.
    GS_SD10-SPART = GS_DATASD10-SPART.
    GS_SD10-SPAKU = GS_DATASD10-SPAKU.
    GS_SD10-SPAKO = GS_DATASD10-SPAKO.
    GS_SD10-SPAAU = GS_DATASD10-SPAAU.
    GS_SD10-HIDE = GS_DATASD10-HIDE.
    MOVE-CORRESPONDING GS_SD10 TO LSS_TVKOS.
    MOVE-CORRESPONDING GS_SD10 TO LS_TASSIGN_SD_VKORG.

    INSERT  TVKOS FROM LSS_TVKOS.
    INSERT  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ENDIF.
ENDFUNCTION.
FORM CHECKSD10.
  DATA:
    LS_TVKO TYPE TVKO,
    I_DATA  TYPE  ZST_BM_SALES_SD08.
  DATA: LSS_TVKOS           TYPE TVKOS,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  I_DATA = GS_DATASD08.
  SELECT SINGLE
    VKORG
      FROM TVKO
      INTO CORRESPONDING FIELDS OF  LS_TVKO
      WHERE VKORG = GS_DATASD08-VKORG.

  IF SY-SUBRC IS INITIAL .
    IF  GS_DATASD10-SPART  IS INITIAL
      AND GS_DATASD10-SPAKU  IS INITIAL
      AND GS_DATASD10-SPAKO  IS INITIAL
      AND GS_DATASD10-SPAAU  IS INITIAL
      AND GS_DATASD10-HIDE  IS INITIAL.
    ELSE.
      GS_SD10-VKORG = GS_DATASD10-VKORG.
      GS_SD10-SPART = GS_DATASD10-SPART.
      GS_SD10-SPAKU = GS_DATASD10-SPAKU.
      GS_SD10-SPAKO = GS_DATASD10-SPAKO.
      GS_SD10-SPAAU = GS_DATASD10-SPAAU.
      GS_SD10-HIDE = GS_DATASD10-HIDE.
      MOVE-CORRESPONDING GS_SD10 TO LSS_TVKOS.
      MOVE-CORRESPONDING GS_SD10 TO LS_TASSIGN_SD_VKORG.

      UPDATE  TVKOS FROM LSS_TVKOS.
      UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
    ENDIF.
  ENDIF.
ENDFORM.
