FUNCTION ZFM_BM_CS_SALES_ORG_SD12.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD12
*"----------------------------------------------------------------------
  DATA: LSS_TVKWZ           TYPE TVKWZ,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  GS_DATASD12 = I_DATA.
  SELECT SINGLE
     TVKWZ~VKORG,
     TVKWZ~VTWEG,
     TVKWZ~WERKS,
     TASSIGN_SD_VKORG~STATUS_ASSIGN_SD
     FROM TVKWZ
     INNER JOIN TASSIGN_SD_VKORG
     ON TASSIGN_SD_VKORG~VKORG = TVKWZ~VKORG
        INTO CORRESPONDING FIELDS OF  @GT_SD12
       WHERE TVKWZ~VKORG = @GS_DATASD12-VKORG
     AND TVKWZ~WERKS = @GS_DATASD12-WERKS
     AND TVKWZ~VTWEG = @GS_DATASD12-VTWEG.

  IF SY-SUBRC IS INITIAL.
    PERFORM CHECKSD12.
    GS_SD12-VKORG = GS_DATASD12-VKORG.
    GS_SD12-VTWEG = GS_DATASD12-VTWEG.
    GS_SD12-WERKS = GS_DATASD12-WERKS.
    MOVE-CORRESPONDING GS_SD12 TO LSS_TVKWZ.
    MOVE-CORRESPONDING GS_SD12 TO LS_TASSIGN_SD_VKORG.

    UPDATE  TVKWZ FROM LSS_TVKWZ.
    UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ELSE.
    GS_SD12-VKORG = GS_DATASD12-VKORG.
    GS_SD12-VTWEG = GS_DATASD12-VTWEG.
    GS_SD12-WERKS = GS_DATASD12-WERKS.
    MOVE-CORRESPONDING GS_SD12 TO LSS_TVKWZ.
    MOVE-CORRESPONDING GS_SD12 TO LS_TASSIGN_SD_VKORG.

    INSERT  TVKWZ FROM LSS_TVKWZ.
    INSERT  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
  ENDIF.
ENDFUNCTION.
FORM CHECKSD12.
  DATA:
    LS_TVKWZ TYPE TVKWZ,
    I_DATA   TYPE  ZST_BM_SALES_SD12.
  DATA: LSS_TVKWZ           TYPE TVKWZ,
        LS_TASSIGN_SD_VKORG TYPE TASSIGN_SD_VKORG.

  I_DATA = GS_DATASD12.
  SELECT SINGLE
    VKORG
      FROM TVKWZ
      INTO CORRESPONDING FIELDS OF  LS_TVKWZ
      WHERE TVKWZ~VKORG = GS_DATASD12-VKORG
      AND TVKWZ~WERKS = GS_DATASD12-WERKS
     AND TVKWZ~VTWEG = GS_DATASD12-VTWEG.

  IF SY-SUBRC IS INITIAL .
    IF GS_DATASD12-VTWEG  IS INITIAL
      AND GS_DATASD12-WERKS  IS INITIAL.
    ELSE.
      GS_SD12-VKORG = GS_DATASD12-VKORG.
      GS_SD12-VTWEG = GS_DATASD12-VTWEG.
      GS_SD12-WERKS = GS_DATASD12-WERKS.
      MOVE-CORRESPONDING GS_SD12 TO LSS_TVKWZ.
      MOVE-CORRESPONDING GS_SD12 TO LS_TASSIGN_SD_VKORG.

      UPDATE  TVKWZ FROM LSS_TVKWZ.
      UPDATE  TASSIGN_SD_VKORG FROM LS_TASSIGN_SD_VKORG.
    ENDIF.
  ENDIF.
ENDFORM.
