FUNCTION ZFM_BM_CS_SALES_ORG_SD102.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD102
*"----------------------------------------------------------------------
DATA: LSS_TVLK       TYPE TVLK.

  GS_DATASD102 = I_DATA.
  SELECT SINGLE
    *
      FROM TVLK
       INTO CORRESPONDING FIELDS OF  GT_SD102
      WHERE LFART = GS_DATASD102-LFART .
  IF SY-SUBRC IS INITIAL.
    GS_SD102-LFART = GS_DATASD102-LFART.
    GS_SD102-FEHGR = GS_DATASD102-FEHGR.

    MOVE-CORRESPONDING GS_SD102 TO LSS_TVLK.
    UPDATE  TVLK FROM LSS_TVLK.

  ELSE.
    GS_SD102-LFART = GS_DATASD102-LFART.
    GS_SD102-FEHGR = GS_DATASD102-FEHGR.

    MOVE-CORRESPONDING GS_SD102 TO LSS_TVLK.
    INSERT  TVLK FROM LSS_TVLK.
  ENDIF.
ENDFUNCTION.
