FUNCTION ZFM_BM_CS_SALES_ORG_SD105.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD105
*"----------------------------------------------------------------------
  DATA: LSS_TVKO      TYPE TVKO.

  GS_DATASD105 = I_DATA.
  SELECT SINGLE
    *
      FROM TVKO
       INTO CORRESPONDING FIELDS OF  GT_SD105
      WHERE VKORG = GS_DATASD105-VKORG .
  IF SY-SUBRC IS INITIAL.
    GS_SD105-VKORG = GS_DATASD105-VKORG.
    GS_SD105-VKOAU = GS_DATASD105-VKOAU.

    MOVE-CORRESPONDING GS_SD105 TO LSS_TVKO.
    UPDATE  TVKO FROM LSS_TVKO.

  ELSE.
    GS_SD105-VKORG = GS_DATASD105-VKORG.
    GS_SD105-VKOAU = GS_DATASD105-VKOAU.

    MOVE-CORRESPONDING GS_SD105 TO LSS_TVKO.
    INSERT  TVKO FROM LSS_TVKO.
  ENDIF.
ENDFUNCTION.
