FUNCTION ZFM_BM_CS_SALES_ORG_SD46 .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD47
*"----------------------------------------------------------------------

DATA: LSS_TVTK        TYPE TVTK.

  GS_DATASD47 = I_DATA.
  SELECT SINGLE
    *
      FROM TVTK
       INTO CORRESPONDING FIELDS OF  GT_SD47
      WHERE SHTYP = GS_DATASD47-SHTYP.
  IF SY-SUBRC IS INITIAL.
    GS_SD47-SHTYP = GS_DATASD47-SHTYP.
    GS_SD47-PARGR = GS_DATASD47-PARGR.
    MOVE-CORRESPONDING GS_SD47 TO LSS_TVTK.
    UPDATE  TVTK FROM LSS_TVTK.

  ELSE.
     GS_SD47-SHTYP = GS_DATASD47-SHTYP.
    GS_SD47-PARGR = GS_DATASD47-PARGR.
    MOVE-CORRESPONDING GS_SD47 TO LSS_TVTK.
    INSERT  TVTK FROM LSS_TVTK.
  ENDIF.
ENDFUNCTION.
