FUNCTION ZFM_BM_CS_05_OKKP.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_05_OKKP
*"----------------------------------------------------------------------
  DATA: LSS_TKA02       TYPE TKA02.

  GS_DATA05_OKKP = I_DATA.
  SELECT SINGLE
    *
      FROM TKA02
       INTO CORRESPONDING FIELDS OF  GT_05_OKKP
      WHERE BUKRS = GS_DATA05_OKKP-BUKRS
    AND GSBER = GS_DATA05_OKKP-GSBER.
  IF SY-SUBRC IS INITIAL.
    GS_05_OKKP-BUKRS = GS_DATA05_OKKP-BUKRS.
    GS_05_OKKP-GSBER = GS_DATA05_OKKP-GSBER.
    GS_05_OKKP-KOKRS = GS_DATA05_OKKP-KOKRS.


    MOVE-CORRESPONDING GS_05_OKKP TO LSS_TKA02.
    UPDATE  TKA02 FROM LSS_TKA02.

  ELSE.
    GS_05_OKKP-BUKRS = GS_DATA05_OKKP-BUKRS.
    GS_05_OKKP-GSBER = GS_DATA05_OKKP-GSBER.
    GS_05_OKKP-KOKRS = GS_DATA05_OKKP-KOKRS.


    MOVE-CORRESPONDING GS_05_OKKP TO LSS_TKA02.
    INSERT  TKA02 FROM LSS_TKA02.
  ENDIF.
ENDFUNCTION.
