FUNCTION ZFM_BM_CS_SALES_ORG_SD52.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD52A
*"----------------------------------------------------------------------
  DATA: LSS_TVPG TYPE TVPG,
        LS_TVPAG TYPE TVPAG.

  GS_DATASD52A = I_DATA.
  SELECT SINGLE
    TVPG~PARGR,
    TVPAG~VTEXT
      FROM TVPG
    INNER JOIN TVPAG
    ON TVPAG~PARGR = TVPG~PARGR
       INTO CORRESPONDING FIELDS OF  @GT_SD52A
      WHERE TVPG~PARGR = @GS_DATASD52A-PARGR.
  IF SY-SUBRC IS INITIAL.

    GS_SD52A-PARGR = GS_DATASD52A-PARGR.
    GS_SD52A-VTEXT = GS_DATASD52A-VTEXT.
    GS_SD52A-PAOBJ = 'F'.
    GS_SD52A-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD52A TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD52A TO LS_TVPAG.

    UPDATE  TVPG FROM LSS_TVPG.
    UPDATE  TVPAG FROM LS_TVPAG.
  ELSE.
    GS_SD52A-PARGR = GS_DATASD52A-PARGR.
    GS_SD52A-VTEXT = GS_DATASD52A-VTEXT.
    GS_SD52A-PAOBJ = 'F'.
    GS_SD52A-SPRAS = SY-LANGU.

    MOVE-CORRESPONDING GS_SD52A TO LSS_TVPG.
    MOVE-CORRESPONDING GS_SD52A TO LS_TVPAG.

    INSERT  TVPG FROM LSS_TVPG.
    INSERT  TVPAG FROM LS_TVPAG.
  ENDIF.
ENDFUNCTION.
