FUNCTION ZFM_BM_CS_SALES_ORG_SDD217.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD217
*"----------------------------------------------------------------------
  DATA:
           LSS_TVFK TYPE TVFK.
  GS_DATASD217 = I_DATA.
  SELECT SINGLE *
    FROM TVFK
    INTO CORRESPONDING FIELDS OF GT_SD217
    WHERE FKART = GS_DATASD217-FKART.
  IF  SY-SUBRC IS INITIAL.
    GS_SD217-FKART = GS_DATASD217-FKART.
    GS_SD217-STATI = GS_DATASD217-STATI.
    MOVE-CORRESPONDING GS_SD217 TO LSS_TVFK.
    UPDATE TVFK FROM LSS_TVFK.
  ELSE.
    GS_SD217-FKART = GS_DATASD217-FKART.
    GS_SD217-STATI = GS_DATASD217-STATI.
    MOVE-CORRESPONDING GS_SD217 TO LSS_TVFK.
    INSERT TVFK FROM LSS_TVFK.
  ENDIF.
ENDFUNCTION.
