FUNCTION ZFM_BM_CS_SALES_ORG_SD103.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD103
*"----------------------------------------------------------------------
DATA: LSS_TVLP      TYPE TVLP.

  GS_DATASD103 = I_DATA.
  SELECT SINGLE
    *
      FROM TVLP
       INTO CORRESPONDING FIELDS OF  GT_SD103
      WHERE PSTYV = GS_DATASD103-PSTYV .
  IF SY-SUBRC IS INITIAL.
    GS_SD103-PSTYV = GS_DATASD103-PSTYV.
    GS_SD103-FEHGR = GS_DATASD103-FEHGR.

    MOVE-CORRESPONDING GS_SD103 TO LSS_TVLP.
    UPDATE  TVLP FROM LSS_TVLP.

  ELSE.
     GS_SD103-PSTYV = GS_DATASD103-PSTYV.
    GS_SD103-FEHGR = GS_DATASD103-FEHGR.

    MOVE-CORRESPONDING GS_SD103 TO LSS_TVLP.
    INSERT  TVLP FROM LSS_TVLP.
  ENDIF.
ENDFUNCTION.
