FUNCTION ZFM_BM_CS_SALES_ORG_SD69.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD69
  DATA: LSS_T683S        TYPE T683S.

  GS_DATASD69 = I_DATA.
  SELECT SINGLE
    *
      FROM T683S
       INTO CORRESPONDING FIELDS OF  GT_SD69
      WHERE KVEWE = GS_DATASD69-KVEWE
    AND KAPPL = GS_DATASD69-KAPPL
    AND KALSM = GS_DATASD69-KALSM
    AND STUNR = GS_DATASD69-STUNR
    AND ZAEHK = GS_DATASD69-ZAEHK.

  IF SY-SUBRC IS INITIAL.
    GS_SD69-KVEWE = 'C'.
    GS_SD69-KAPPL = 'V'.
    GS_SD69-KALSM = GS_DATASD69-KALSM.
    GS_SD69-STUNR = GS_DATASD69-STUNR.
    GS_SD69-ZAEHK = GS_DATASD69-ZAEHK.
    GS_SD69-KSCHL = GS_DATASD69-KSCHL.
    GS_SD69-KOBED = GS_DATASD69-KOBED.
    GS_SD69-KAUTO = GS_DATASD69-KAUTO.
    MOVE-CORRESPONDING GS_SD69 TO LSS_T683S.
    UPDATE  T683S FROM LSS_T683S.

  ELSE.
    GS_SD69-KVEWE = 'C'.
    GS_SD69-KAPPL = 'V'.
    GS_SD69-KALSM = GS_DATASD69-KALSM.
    GS_SD69-STUNR = GS_DATASD69-STUNR.
    GS_SD69-ZAEHK = GS_DATASD69-ZAEHK.
    GS_SD69-KSCHL = GS_DATASD69-KSCHL.
    GS_SD69-KOBED = GS_DATASD69-KOBED.
    GS_SD69-KAUTO = GS_DATASD69-KAUTO.
    MOVE-CORRESPONDING GS_SD69 TO LSS_T683S.
    INSERT  T683S FROM LSS_T683S.
  ENDIF.
ENDFUNCTION.
