FUNCTION ZFM_BM_CS_SALES_ORG_SD98.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ZST_BM_SALES_SD98
*"----------------------------------------------------------------------

  DATA: LSS_TVAP          TYPE TVAP.

  GS_DATASD98 = I_DATA.
  SELECT SINGLE
    *
      FROM TVAP
       INTO CORRESPONDING FIELDS OF  GT_SD98
      WHERE PSTYV = GS_DATASD98-PSTYV .
  IF SY-SUBRC IS INITIAL.
    GS_SD98-PSTYV = GS_DATASD98-PSTYV.
    GS_SD98-FEHGR = GS_DATASD98-FEHGR.
    MOVE-CORRESPONDING GS_SD98 TO LSS_TVAP.
    UPDATE  TVAP FROM LSS_TVAP.

  ELSE.
    GS_SD98-PSTYV = GS_DATASD98-PSTYV.
    GS_SD98-FEHGR = GS_DATASD98-FEHGR.
    MOVE-CORRESPONDING GS_SD98 TO LSS_TVAP.
    INSERT  TVAP FROM LSS_TVAP.
  ENDIF.
ENDFUNCTION.
