*&---------------------------------------------------------------------*
*& Include ZIN_BM_TRAN_TAB_TOP            Report ZPG_BM_TRAN_TAB
*&
*&---------------------------------------------------------------------*

TYPES:
  BEGIN OF GTY_OBJECT,
    OBJNAME TYPE TABNAME,
  END OF GTY_OBJECT,
  BEGIN OF GTY_TCODE,
    TCODE TYPE TCODE,
  END OF GTY_TCODE,

  BEGIN OF GTY_VCL_NAME,
    VCL_NAME TYPE VCL_NAME,
  END OF GTY_VCL_NAME,
  BEGIN OF GTY_VIEW_INFO,
    TABNAME   TYPE DD02L-TABNAME,
    TABCLASS  TYPE DD02L-TABCLASS,
    CLIDEP    TYPE DD02L-CLIDEP,
    MAINFLAG  TYPE DD02L-MAINFLAG,
    VIEWCLASS TYPE DD02L-VIEWCLASS,
    ROOTTA    TYPE DD25L-ROOTTAB,
  END OF GTY_VIEW_INFO.

TABLES: ZTB_BM_CSTR_M, ZTB_BM_CSTR_C.
TABLES: TADIR.

DATA: GT_KEY TYPE APB_LPD_T_E071K,
      GT_OBJ TYPE /SAPCND/T_KO200.

SELECTION-SCREEN BEGIN OF BLOCK BLK_ROUTE WITH FRAME TITLE TEXT-001 .
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS:
      P_TRATR  RADIOBUTTON GROUP RG2 DEFAULT 'X' USER-COMMAND TRA  MODIF ID TRA.
    SELECTION-SCREEN COMMENT 3(20)  FOR FIELD P_TRATR  MODIF ID TRA.
    PARAMETERS:
      P_TRADL  RADIOBUTTON GROUP RG2  MODIF ID TRA.
    SELECTION-SCREEN COMMENT 25(15) FOR FIELD P_TRADL  MODIF ID TRA.
    SELECTION-SCREEN POSITION 45.
    PARAMETERS:
      P_TRAUL  RADIOBUTTON GROUP RG2  MODIF ID TRA.
    SELECTION-SCREEN COMMENT 50(15) FOR FIELD P_TRAUL  MODIF ID TRA.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK BLK_ROUTE.

SELECTION-SCREEN BEGIN OF BLOCK BLK_DATA WITH FRAME TITLE TEXT-002.
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS:
      P_PDFCS  RADIOBUTTON GROUP RG1 DEFAULT 'X' USER-COMMAND STY  MODIF ID STY.
    SELECTION-SCREEN COMMENT 3(20)  FOR FIELD P_PDFCS  MODIF ID STY.
    PARAMETERS:
      P_STABL  RADIOBUTTON GROUP RG1  MODIF ID STY.
    SELECTION-SCREEN COMMENT 25(15) FOR FIELD P_STABL  MODIF ID STY.
  SELECTION-SCREEN END OF LINE.

SELECT-OPTIONS:
  S_MODLID  FOR ZTB_BM_CSTR_C-MODLID MODIF ID TCS,
  S_CSFUNC  FOR ZTB_BM_CSTR_C-CSFUNC MODIF ID TCS,
  S_TABNM   FOR ZTB_BM_CSTR_C-VIEWNAME MODIF ID TTB.
SELECTION-SCREEN END OF BLOCK BLK_DATA.
