*&---------------------------------------------------------------------*
*& Include ZIN_BM_CS_COMPANYCODETOP                 - Report ZPG_BM_CS_COMPANYCODE
*&---------------------------------------------------------------------*
REPORT ZPG_BM_CS_COMPANYCODE.


DATA:
  GT_T001       TYPE   T001,
  G_MODE        TYPE STRING,
  GV_BUKRS      TYPE BUKRS,
  GV_BUTXT      TYPE BUTXT,
  GV_ORT01      TYPE ORT01,
  GV_LAND1      TYPE LAND1,
  GV_WAERS      TYPE WAERS,
  GV_SPRAS      TYPE SPRAS,
  GV_TITLE_MEDI TYPE AD_TITLE,
  GV_NAME1      TYPE AD_NAME1,
  GV_NAME2      TYPE AD_NAME2,
  GV_SORT1      TYPE AD_SORT1UL,
  GV_SORT2      TYPE AD_SORT2UL,
  GV_STR_SUPPL1 TYPE AD_STRSPP1,
  GV_STREET     TYPE AD_STREET,
  GV_POST_CODE1 TYPE AD_PSTCD1,
  GV_CITY1      TYPE AD_CITY1,
  GV_COUNTRY    TYPE LAND1,
  GV_REGION     TYPE REGIO,
  GV_TIME_ZONE  TYPE AD_TZONE,
  GV_PO_BOX     TYPE AD_POBX,
  GV_POST_CODE2 TYPE AD_PSTCD2,
  GV_POST_CODE3 TYPE AD_PSTCD3,
  GV_LANGU      TYPE SPRAS,
  GV_DEFLT_COMM TYPE AD_COMM,
  GV_REMARK     TYPE AD_REMARK1,
  GV_TEL_NUMBER TYPE AD_TLNMBR1,
  GV_TEL_EXTENS TYPE AD_TLXTNS1,
  GV_MOB_NUMBER TYPE AD_MBNMBR1,
  GV_FAX_NUMBER TYPE AD_FXNMBR1,
  GV_FAX_EXTENS TYPE AD_FXXTNS1,
  GV_ADRNR      TYPE ADRNR,
  GV_SMTP_ADDR  TYPE AD_SMTPADR.

DATA:
  GS_DATA   TYPE   ZST_BM_V_T001_ADDRESS,
  GT_RETURN TYPE  TABLE OF BAPIRET2.
DATA: ADTEL_WA TYPE SZADR_ADTEL_LINE.




DATA: BEGIN OF E_TABLE OCCURS 0.
        INCLUDE STRUCTURE ADDR_ERROR.
DATA: END OF E_TABLE.
DATA: BEGIN OF ADTEL OCCURS 0.
        INCLUDE STRUCTURE ADTEL.
DATA: END OF ADTEL.
DATA: BEGIN OF ADFAX OCCURS 0.
        INCLUDE STRUCTURE ADFAX.
DATA: END OF ADFAX.
DATA: BEGIN OF ADSMTP OCCURS 0.
        INCLUDE STRUCTURE ADSMTP.
DATA: END OF ADSMTP.

TYPES:

  BEGIN OF SZADR_ADTEL_LINE,
    DATE_FROM LIKE ADRC-DATE_FROM,
    ADTEL     LIKE ADTEL,
  END OF SZADR_ADTEL_LINE.
