
*&---------------------------------------------------------------------*
*& Include ZIN_BM_CS_PROJECTTOP                     - Report ZPG_BM_CS_PROJECT
*&---------------------------------------------------------------------*
REPORT ZPG_BM_CS_PROJECT.





DATA
      GT_ALV    TYPE TABLE OF ZST_BM_CSPJ_P.
DATA:
      GT_CSPJ_D   TYPE TABLE OF ZST_BM_CSPJ_D.
DATA
GT_RESELECT        TYPE TABLE OF ZST_BM_CSTR_M.


TABLES: ZTB_BM_CSPJ_P.
SELECT-OPTIONS :
       S_PROJID FOR ZTB_BM_CSPJ_P-PROJID.





DATA :

  GT_FIELDCAT         TYPE LVC_T_FCAT,
  GT_FIELDCAT1        TYPE LVC_T_FCAT,
  GS_FIELDCAT         TYPE LVC_S_FCAT,
  GS_FIELDCAT1        TYPE LVC_S_FCAT,
  GS_LAYOUT           TYPE LVC_S_LAYO,
  GV_MODLID           TYPE ZDD_BM_MODULE,
  GV_PROJID           TYPE ZDD_BM_CS_PROJID,
  GV_DESCR            TYPE ZDD_BM_DESCR,
  GV_DATBE            TYPE DATE_START,
  GV_DATEN            TYPE DATE_END,
  GT_LIST             TYPE  CCSEQ_T_VALUES,
  GT_LIST1            TYPE  CCSEQ_T_VALUES,
  G_MODE              TYPE CHAR2,
  G_HIDE              TYPE C,
  G_LOCK              TYPE C,
  GS_STYLE            TYPE LINE OF LVC_T_STYL,
  GV_FREE1            TYPE CHAR1,


  G_CUSTOM_CONTAINER  TYPE REF TO   CL_GUI_CUSTOM_CONTAINER,
  G_CUSTOM_CONTAINER1 TYPE REF TO   CL_GUI_CUSTOM_CONTAINER,
  G_CONTAINER         TYPE          SCRFNAME VALUE 'CONTAINER',
  G_CONTAINER1        TYPE          SCRFNAME VALUE 'RESELECT',
  G_ALV_GRID          TYPE REF TO   CL_GUI_ALV_GRID,
  G_ALV_GRID1         TYPE REF TO   CL_GUI_ALV_GRID.

CLASS ZCL_EVENT_HANDLER DEFINITION.
  PUBLIC SECTION.
    CLASS-METHODS: BUTTON_CLICK
      FOR EVENT BUTTON_CLICK OF CL_GUI_ALV_GRID
      IMPORTING ES_COL_ID
                ES_ROW_NO.
ENDCLASS.
TYPES:
  BEGIN OF GTY_CSPJ_C,
    PROJID   TYPE ZTB_BM_CSPJ_C-PROJID,
    MODLID   TYPE ZTB_BM_CSPJ_C-MODLID,
    CSFUNC   TYPE ZTB_BM_CSPJ_C-CSFUNC,
    TCODE    TYPE ZTB_BM_CSTR_C-TCODE,
    STTURE   TYPE ZTB_BM_CSPJ_C-STTURE,
    VCL_NAME TYPE ZTB_BM_CSPJ_C-VCL_NAME,
    VIEWNAME TYPE ZTB_BM_CSPJ_C-VIEWNAME,
    SUMREC   TYPE ZTB_BM_CSPJ_C-SUMREC,
    COMREC   TYPE ZTB_BM_CSPJ_C-COMREC,
    CSFSTS   TYPE ZTB_BM_CSPJ_C-CSFSTS,
    CRUSR    TYPE ZTB_BM_CSPJ_C-CRUSR,
    CRDAT    TYPE ZTB_BM_CSPJ_C-CRDAT,
    CRTIM    TYPE ZTB_BM_CSPJ_C-CRTIM,
    CHUSR    TYPE ZTB_BM_CSPJ_C-CHUSR,
    CHDAT    TYPE ZTB_BM_CSPJ_C-CHDAT,
    CHTIM    TYPE ZTB_BM_CSPJ_C-CHTIM,
    DESCR    TYPE  ZTB_BM_CSTR_C-DESCR,
  END OF GTY_CSPJ_C.
